### ISSUE TITLE
Add alt-texts for the impressions

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#100]
We should also add alt-attributes for the impression pictures.

- [x] Write short descriptions of the photos English and German
- [x] add the texts to the page.

**Comment by splattater** [comment]
Alt textes for impressions are online now, but I don't know how the screen readers will cope with the js of the slideshow.
@JuliaHolze if you want to write nicer descriptions you can edit the statements starting here :-) https://github.com/AKSW/leipzig.dataweek.de-model/blob/fe807f1acca2397de7e8872589d093e6d709419a/event.ttl#L733

**Comment by white-gecko** [comment]
Please see the comments in #119 .
