### ISSUE TITLE
Add CfP - LSWT 2023

### ISSUE THREAD

**Issue by JuliaHolze** [AKSW/leipzig.dataweek.de#102]
Update 2023-02-14:

- [x] [CalForPosters-LSWT2023.pdf](https://github.com/AKSW/leipzig.dataweek.de/files/10732758/CalForPosters-LSWT2023.pdf)
- [x] [CfP-LSWT2023.pdf](https://github.com/AKSW/leipzig.dataweek.de/files/10732759/CfP-LSWT2023.pdf)

**Comment by TBoonX** [comment]
Wo soll der Link dazu auftauchen?

**Comment by white-gecko** [comment]
Ungefär so:

![image](https://user-images.githubusercontent.com/1018168/217766976-1d60e2c8-d8d9-484d-92c6-46937876e159.png)

**Comment by white-gecko** [comment]
@JuliaHolze could you organize a German translation for the calls? Maybe could you also go through the English text on this occasion?

**Comment by JuliaHolze** [comment]
@white-gecko please add the German translation on the lswt website

Der Leipziger Semantic Web Tag (LSWT) bietet seit 2009 WissenschaftlerInnen, Unternehmen und Organisationen die Möglichkeit, sich zu Themen im Bereich semantischer Technologien auszutauschen. In diesem Jahr findet der LSWT wieder gemeinsam mit der 2. Data Week Leipzig statt, einer einwöchigen Veranstaltung in Leipzig, die sich mit den Herausforderungen von Daten, Digitalisierung, künstlicher Intelligenz und Stadtentwicklung beschäftigt.

Während der LSWT werden wir die neuesten Entwicklungen und Trends in den Bereichen semantische Technologien und Daten hervorheben. Schwerpunkte in diesem Jahr sind Wissensgraphen, E-Government, Geodaten, temporale Daten, ESG, Mobilität, vernetzte Gesellschaft, Datenintegration, Semantic Web in der Industrie und künstliche Intelligenz. Diese Schwerpunkte werden in Vorträgen von Experten aus Wirtschaft und Wissenschaft vorgestellt.

Falls Sie weitere Fragen haben, können Sie sich gern an das Organisationsteam wenden.

### Aufruf an zukünftige Experten für semantische Technologien
Liebe Kolleg:innen,

wir veranstalten auch eine interaktive Postersession mit Studierenden. Jede/r Student:in bzw. jede Gruppe von Studierenden muss mit einem gedruckten Poster über seine/ihre aktuelle Arbeit zu der Veranstaltung kommen. Studierende halten eine kurze Präsentation und stellen die Poster in den Pausen den interessierten Teilnehmenden vor. Am Ende des Tages findet eine Posterpreisverleihung (gesponsert von der eccenca GmbH) mit einem Geldpreis statt. Die Poster werden nach folgenden Kriterien bewertet: bester Inhalt und beste Gestaltung. Nachfolgend weitere Informationen zu den Vorgaben:

* Die Plakate müssen ein konferenzbezogenes Thema behandeln
* Die Poster sollten ein vertikales Design haben
* Die empfohlene Postergröße ist: DIN A0

Wenn Sie interessiert sind, sprechen Sie bitte mit Ihrem Professor. Dort erhalten Sie weitere Informationen zu den Reisekosten und zur Anmeldung. Sie können uns auch unter lswt@infai.org kontaktieren.

Wir freuen uns darauf, Sie in Leipzig zu treffen.

### Aufruf zur Teilnahme
Sind Sie bereit, einen Beitrag zu leisten? Wenn ja, laden wir Sie ein, Ihre aktuelle Arbeit in einem 15-minütigen Vortrag vorzustellen. Beiträge, die sich mit Frauen im Bereich Data Sciece befassen, sind herzlich willkommen. Die Präsentationen werden in englischer Sprache gehalten.

Neben einer Keynote-Präsentation und mehreren Sessions werden wir auch eine interaktive Postersession mit studentischen Arbeiten veranstalten. Bitte leiten Sie daher unseren Aufruf zur Einreichung von Postern an alle interessierten Studierende weiter.

Wir freuen uns auf Ihre Beiträge, damit diese Veranstaltung ein Erfolg wird! Bitte senden Sie Ihre Ideen für eine Präsentation bis zum 12. Mai 2023 an lswt@infai.org.

Wenn Sie weitere Fragen haben, zögern Sie nicht, uns zu kontaktieren. Wir freuen uns darauf, Sie in Leipzig zu treffen.

**Comment by JuliaHolze** [comment]
[CallForParticipation_en_de.pdf](https://github.com/AKSW/leipzig.dataweek.de/files/10757788/CallForParticipation_en_de.pdf)
[CallForPosters_en_de.pdf](https://github.com/AKSW/leipzig.dataweek.de/files/10757790/CallForPosters_en_de.pdf)
