### ISSUE TITLE
No video preview shown

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#110]
On *https://staging.dataweek.de/*

![image](https://user-images.githubusercontent.com/1018168/217496618-4eb1423f-b3f6-447d-b287-cba6bf2eeffb.png)

I guess there is some (minimum) height missing.
Maybe this is also due to the new content policy: https://github.com/AKSW/leipzig.dataweek.de/commit/c3518fcec65ea7255f22d0dc596181287c005d81

**Comment by TBoonX** [comment]
The meta tag also makes local running/serve impossible. Is the security impact big enough to justify the issues it generates?

**Comment by white-gecko** [comment]
I just have to understand it. Or someone else understands it … I have removed the tag for now.
