### ISSUE TITLE
Add Subevents to the mobile main navigation

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#111]
The subevents LSWT, … are missing in the main navigation but this is setup in the layout already:
![image](https://user-images.githubusercontent.com/1018168/217531577-9a471831-a2be-448d-9b2f-b18c82841ac8.png)

**Comment by white-gecko** [comment]
@TBoonX or @splattater who would be able to take this ticket?

**Comment by splattater** [comment]
The subevents will be part of the program menu.
The last time I worked on the program I already had the correct entries, links and html pages.
