### ISSUE TITLE
Programmbereich A and B is not available on mobile

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#114]
The programmbereich switch is not available on mobile devices.

![image](https://user-images.githubusercontent.com/1018168/217568055-6e0d3663-fa86-4848-875f-6f5c3004e318.png)

![image](https://user-images.githubusercontent.com/1018168/217568104-4d15d052-dff6-4c40-9845-27546977e6d1.png)

**Comment by dannyotto** [comment]
This switch was for more than one event on the same day. With your implementation the switch isn't necessary. You use for every event a new tab.

**Comment by dannyotto** [comment]
<img width="506" alt="2023-02-13" src="https://user-images.githubusercontent.com/869758/218529605-592179aa-4e9c-4f5e-872f-004da8e122dc.png">

The navigation now has on mobils a new design and can show a second level.

**Comment by white-gecko** [comment]
@dannyotto I have added the updated css files and removed the selection form for the mobile menu. But we have stillt trouble getting the active menu entry highlighted: https://staging.dataweek.de/en/lswt2023/


![grafik](https://user-images.githubusercontent.com/1018168/219035540-cef184a2-ab48-4fd4-9a5b-eb045257b705.png)

Further I would switch the day of the week and the name of the event in the mobile presentation. How could I achieve this? Also some extra space would be required.

**Comment by dannyotto** [comment]
https://prototype.pixelbrand.co/dataweek/programm_montag.html

For the current page you have to use `<strong>`. And the extra space you achieve with a blank character in HTML. This character is also needed for screenreaders.

Regarding the order: I see why you want to switch it. But we shouldn't change the order from one breakpoint to another. We also use this order in the mobile Navigation and on the programm page. If it's really necessary, I must wrap the event title with an additional tag and then I can change the order with flexbox.

**Comment by white-gecko** [comment]
If I add `<strong>` I get an extra item bullet, the text is not orange, and in the desktop view the tab is getting wider.

![grafik](https://user-images.githubusercontent.com/1018168/219322753-58624e4e-f188-4813-89e6-1e67ce311284.png)
![grafik](https://user-images.githubusercontent.com/1018168/219323055-21a99771-d82a-46bd-b71a-255cdc4ca9c2.png)

Could you please provide an example of an active top level menu entry?

Regarding the order of the title and the date: would it also be possible to put the title first, followed by the date and wrap the date in an extra tag and let it flow to the top of the tab in the desktop view? Would that make sense and work out good?

**Comment by dannyotto** [comment]
You can find the example there:
https://prototype.pixelbrand.co/dataweek/programm_montag.html
https://prototype.pixelbrand.co/dataweek/programm_montag_bereich-a.html

**Comment by white-gecko** [comment]
Ok, thanks, we had an a-tag, which obviously destroyed the layout. Now it works.

So there is only the issue with the sorting of the title and the date left.

**Comment by dannyotto** [comment]
I change now the order of title and date in html. On desktop I flipped it back with flexbox.

**Comment by white-gecko** [comment]
Thank you, the swap worked, but now the highlight color is gone.

Before:
![image](https://user-images.githubusercontent.com/1018168/220071776-5611ce21-4657-4b89-93b2-ab405a41e1e0.png)
After:
![image](https://user-images.githubusercontent.com/1018168/220071831-0374cd01-4fad-491d-a4ad-4c76ccd63af7.png)

(https://staging.dataweek.de/eid-2023/)

**Comment by dannyotto** [comment]
Sorry. Apparently I had only checked the subpages.

**Comment by white-gecko** [comment]
Thank you. Fixed with 163bd49497c58a47d849bd5d45826e84adc81e75.
