### ISSUE TITLE
Multiday Event in the tabs

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#116]
Tabs again ;-)

We will have one event over two days (#112)

What is your suggestion to represent this in the tabs?

This would not work:

![image](https://user-images.githubusercontent.com/1018168/217572477-118a55e4-e594-4b06-896c-3670895aed07.png)

![image](https://user-images.githubusercontent.com/1018168/217572824-7dc05ccc-90ea-4ba9-b3f5-9685dbb4594b.png)

**Comment by white-gecko** [comment]
ScaDS event is on three days. So @JuliaHolze and I have decided, that we switch to just "Mo., Di. & Do." resp. "Mon, Tur & Thu". But still there will be the same problem but with less text. I will provide a screenshot once I made this change.

**Comment by white-gecko** [comment]
No, everything is fine:
![grafik](https://user-images.githubusercontent.com/1018168/218463600-1d6185dc-e64f-4887-a49b-62dfa80298da.png)

even with 978
![grafik](https://user-images.githubusercontent.com/1018168/218463700-107ae16d-979c-42d4-aa47-ea9275ff587f.png)

**Comment by dannyotto** [comment]
Looks nice!
