### ISSUE TITLE
Fancy Image on start page needs to long to load

### ISSUE THREAD

**Issue by MichaelMartin** [AKSW/leipzig.dataweek.de#117]
If you initially load the dataweek website it needs much to long to load the image.

**Comment by white-gecko** [comment]
I don't understand why. Just loading https://2023.dataweek.de/resources/images/Leipzig.jpg is pretty fast for me.

Any ideas @dannyotto ?

**Comment by dannyotto** [comment]
The image filesize looks a bit high. Can you try to compress the jpg?

https://2023.dataweek.de/resources/images/Leipzig_1980.jpg

3.4 MB

**Comment by dannyotto** [comment]
<img width="1046" alt="Bildschirm­foto" src="https://user-images.githubusercontent.com/869758/217842193-7a0a1a5f-fe60-4fd8-81fa-da6badb4c25d.png">

**Comment by white-gecko** [comment]
Ok, I think:

```
convert Leipzig_1980.jpg -sampling-factor 4:2:0 -strip -quality 82 -interlace JPEG -colorspace sRGB Leipzig_1980_comp.jpg
```
(Inspired by https://github.com/OrlovEvgeny/TinyJPG/blob/master/compress/convert.go ;-) )

would do the trick with even less artifacts.

**Comment by white-gecko** [comment]
@MichaelMartin pleas check on https://staging.dataweek.de/ is it better now?

**Comment by white-gecko** [comment]
Since there is no answer I will close that issue now.
