### ISSUE TITLE
add AI-T German translation

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#125]
The contents of
https://staging.dataweek.de/ai-tomorrow-2023/
need to be translated to German.

**Comment by JuliaHolze** [comment]
### Konferenz zu „Artificial Intelligence Development for a Resilient and Sustainable Tomorrow“


Die erste Konferenz zu Artificial Intelligence Development for a Resilient and Sustainable Tomorrow (Künstliche Intelligenz Entwicklung für ein widerstandsfähiges und nachhaltiges Morgen) ([www.kmi-leipzig.de/kmi-projekt/ai-tomorrow/](http://www.kmi-leipzig.de/kmi-projekt/ai-tomorrow/)) wird vom Kompetenzzentrum KMI in Kooperation mit verschiedenen Partnern organisiert. Die Konferenz ist Teil der DataWeek Leipzig ([www.dataweek.de](http://www.dataweek.de/)) und wird vom 29. bis 30. Juni 2023 stattfinden.

### Motivation
Digitale Innovationen verändern die Funktionsweise von Gesellschaften. Durch den Einsatz digitaler Technologien entstehen neue Möglichkeiten, darunter ein verbesserter Wissenszugang, eine umfassendere Produktentwicklung, die Schaffung neuer Geschäftsfelder und der Abbau von Bürokratie. Die digitale Transformation geht über reine technologische Verbesserungen hinaus und betrifft das gesamte Unternehmen und seine Mitarbeiter im Hinblick auf die Neugestaltung von Prozessen, Geschäftsmodellen und Organisationsstrukturen. Kommunikation und Kollaboration sowie Informationsprozesse, industrielle Prozesse und Anforderungen ändern sich. Um wettbewerbsfähig zu bleiben, müssen sich Unternehmen auf der ganzen Welt an diese rasanten Entwicklungen anpassen. Dies erfordert eine multidisziplinäre Herangehensweise an die digitale Transformation.
In Deutschland haben kleine und mittlere Unternehmen (KMU) einen großen Einfluss auf die Wirtschaft. Der Anteil der KMU in Deutschland im Jahr 2019 lag bei 99,4 Prozent [1]. Sie machen den Großteil aller Lehrlingsausbildungen aus und sind damit einer der Haupttreiber der Kompetenzentwicklung [2]. Während große Unternehmen die finanziellen Möglichkeiten haben, Change Manager einzustellen und in Beratung und Schulung zu investieren, kämpfen KMU mit der Geschwindigkeit der Entwicklung und haben nicht die finanziellen und personellen Ressourcen für die Anpassung. Um mit größeren Unternehmen in Bezug auf erschwingliche Preise und qualitativ hochwertige Produkte konkurrieren zu können, müssen sich KMU an neue digitale Innovationen anpassen. Der Einsatz von Künstlicher Intelligenz (KI) – eine der Schlüsseltechnologien der Digitalisierung – kann den Geschäftserfolg maßgeblich beeinflussen und wird zunehmend zum Game Changer für den Mittelstand. Im Gegensatz dazu zeigt die Studie von Accenture aus dem Jahr 2022 [3], dass nur zwölf Prozent der Unternehmen ihren KI-Reifegrad für hoch genug halten, um damit ihr Geschäft auszubauen und zu transformieren, während sich 63 Prozent noch in der experimentellen Phase der Einführung von KI in Unternehmen befinden.

Neben den Herausforderungen der digitalen Transformation haben aktuelle Entwicklungen und Krisen wie KI-Verordnungen der EU, gestörte Lieferketten, Fachkräftemangel und Klimawandel den Fokus erweitert und hinterfragen die Auswirkungen und Chancen der Digitalisierung mit Blick auf den nächsten Evolutionsschritt in der Entwicklung von Industrie 4.0, nämlich Industrie 5.0. In einem Whitepaper aus dem Jahr 2021 beschreibt die Europäische Kommission Industrie 5.0 als „zukunftssicherer, widerstandsfähiger, nachhaltiger und menschenorientierter“[4]. Während Industrie 4.0 die Resilienz steigere und „die positiven Auswirkungen auf die ökologische und ökonomische Dimension ziemlich weit verbreitet zu sein scheinen“, werde die soziale Dimension, insbesondere menschenzentrierte Ansätze und Maßnahmen, möglicherweise noch unterschätzt. Menschen bzw. menschzentrierte Ansätze sind daher der Haupttreiber und Innovationsfaktor für Industrie 5.0. Ein menschzentrierter Ansatz für die digitale Transformation bedeutet, sich auf die Bedürfnisse und Interessen der Menschen zu konzentrieren, anstatt die Technologie als alleinigen Akteur zu betrachten.

### Ziel
Das Ziel der Arbeitskonferenz zu Artificial Intelligence Development for a Resilient and Sustainable Tomorrow ist es, Forscher zusammenzubringen, um die ökologischen, sozialen und wirtschaftlichen Auswirkungen des Designs, der Entwicklung und des Einsatzes von KI in der Industrie 5.0 zu diskutieren. Wir konzentrieren uns auf menschenzentrierte Ansätze in der KI-Entwicklung; eine multidimensionale Wertediskussion über Auswirkungen und Nachhaltigkeit von KI; Messungen für KI-Werte; konkrete Anwendungsfälle der KI-Entwicklung (in KMU) und ihre Auswirkungen. Indem wir Experten aus verschiedenen Bereichen zusammenbringen, fördern wir den interdisziplinären Dialog und identifizieren Möglichkeiten für die Zusammenarbeit und den Fortschritt bei der verantwortungsvollen Entwicklung und dem Einsatz von KI.

### CFP
Die interdisziplinäre Konferenz begrüßt Beiträge aus Informatik, Sozialwissenschaften, Recht, Politik und Technik, um nur einige zu nennen. Alle Einsendungen müssen unveröffentlicht sein und dürfen nicht an anderer Stelle im Reviewprozess sein. AI-Tomorrow bietet ein doppelblindes Peer-Review-Verfahren für alle Forschungsarbeiten. Autoren dürfen in Beiträgen weder explizit noch implizit (z. B. durch einen Hinweis auf die Förderung in den Danksagungen) genannt werden. Die Gutachter haben keinen Zugriff auf die Namen der Autoren.
Der Tagungsband wird bei Springer Open Access veröffentlicht. Daher sollte das LNCS-Template verwendet werden: https://www.springer.com/gp/computer-science/lncs/conference-proceedings-guidelines.
Beiträge sollten (in Englisch) im PDF-Format mit einem Umfang von 6 bis 10 Seiten eingereicht werden, einschließlich 10 Leerzeilen direkt vor den Referenzen für die Veröffentlichung in Open Access. Zusätzlich ist eine Zusammenfassung von einer halben Seite in deutscher Sprache erforderlich. Nicht deutschsprachige Personen können sich gerne an uns wenden, um Hilfe zu erhalten.

Wichtige Daten:
* Paper Einreichung bis: 01 April 2023 
* Review der Paper bis: 14 Mai 2023
* Benachrichtigung über Annahmen bis: 24 Mai 2023
* Einreichung der Camera-ready Paper bis: 01 Juni 2023
* Konferenz in Leipzig: 29. bis 30. Juni 2023
	Fragen können bitte an [kmi-project@infai.org](mailto:kmi-project@infai.org) gerichtet werden.

Easychair### 
* Call for Paper: https://easychair.org/cfp/AI_Tomorrow_23
* Einreichung: https://easychair.org/conferences/?conf=aitomorrow23

### Themen
Es sind Beiträge aus unterschiedlichen Disziplinen wie Informatik, Sozialwissenschaften, Recht, Politik sowie Ingenieurwissenschaften erwünscht. Dieses breite Spektrum an Disziplinen ermöglicht, sowohl den interdisziplinären Charakter der Forschung als auch die Weiterentwicklung von KI-Entwicklungen und Industrie 5.0 voranzutreiben:
* Digital transformation of organisations or processes trough AI 
* XAI
* Human-centred approaches of AI design & development
* Ethics, security, and trust in algorithms that influence work
* Smart Systems
* HCI/HMI
* AI and multiple value creation
* Future Skills in work with regard to AI
* Sustainable AI Applications and case studies in multiple fields
* Manufacturing and factories of the future
* Health care
* Food and Agriculture
* Crisis and disaster management
* Supply chains
* E-government
* Urban logistics and smart cities
* Energy systems
* Education

**Comment by white-gecko** [comment]
Done
