### ISSUE TITLE
Program comprehensive information

### ISSUE THREAD

**Issue by splattater** [AKSW/leipzig.dataweek.de#131]
We can put some information for each day under the program heading e.g. which events take place at which venues
![Bildschirmfoto vom 2023-02-16 13-51-16](https://user-images.githubusercontent.com/1556061/219372775-a43827ba-6f10-41c3-b1d1-132e34a4a825.jpg)

**Comment by JuliaHolze** [comment]
Montag 
OGC richtet das Tagesprogramm unter dem Motto “EU Green Deal Data Space” im Sitzungssaal und im Festsaal. Parallel dazu bietet Scads.AI ein Training im Ratsplenarsaal zur Datenvisualisierung an. Der Workshop “Green Deal Datenräume” findet im Raum 259 statt.  

Monday
OGC hosts the day's program under the motto "EU Green Deal Data Space" in the Sitzungssaal and the Festsaal. In parallel, Scads.AI offers training on data visualization in the Council Plenary Room. The workshop "Green Deal Data Spaces" will take place in room 259.


Dienstag
Der 2. Konferenztag steht unter dem Motto “Daten befreien! Kompetenzen und Tools für klimaangepasste Städte”. Eröffnet wird dieser mit einer spannenden Keynote Präsentation und Preisverleihung. Das Konferenzprogramm findet parallel im Sitzungssaal und Ratsplenarsaal statt, wobei der Workshop “Geodatengestütztes Ökosystem” im Raum 259 abgehalten wird. 

Tuesday
The 2nd conference day is themed "Free data! Competencies and Tools for Climate-Adapted Cities". This will open with an exciting keynote presentation and awards ceremony. The conference program will take place in parallel in the Sitzungssaal and Ratsplenarsaal (council plenary room), with the "Geospatial Ecosystem" workshop being held in room 259.


Mittwoch
Für die Veranstaltungen Leipziger Semantic Web Tag (Sitzungssaal), Data Science Mania (Festsaal) und das KMI Konsortialtreffen (Ratsplenarsaal) kommen am 3. Tag verschiedene Akteure zusammen. Das Scads.AI Training zur Programmiersprache Python für die Mitarbeiter:innen der Stadt Leipzig findet im Raum 260 statt. Der OGC Semantic Workshop wird im Raum 259 abgehalten.   

Wednesday
For the events Leipzig Semantic Web Day (Sitzungssaal), Data Science Mania (Festsaal) and the KMI Consortium Meeting (Festsaal/ council plenary room), various stakeholders will come together on Day 3. Scads.AI training on the Python programming language for City of Leipzig staff will be held in room 260. The OGC Semantic Workshop will be held in room 259.


Donnerstag
Die Arbeitskonferenz “Künstliche Intelligenz Entwicklung für ein widerstandsfähiges und nachhaltiges Morgen” (AI Tomorrow) bringt Forscher:innen im Ratsplenarsaal zusammen, um die ökologischen, sozialen und wirtschaftlichen Auswirkungen des Designs, der Entwicklung und des Einsatzes von KI in der Industrie 5.0 wissenschaftlich zu diskutieren. Parallel dazu findet das Scads.AI Training “Grundlagen Machine Learning mit Python” im Raum 259 statt. 

Thursday
The working conference on "Artificial Intelligence Development for a Resilient and Sustainable Tomorrow" (AI Tomorrow) will bring together researchers in the Ratsplenarsaal (council plenary room) to discuss the environmental, social and economic implications of the design, development and deployment of AI in Industry 5.0. In parallel, the Scads.AI training "Fundamentals Machine Learning with Python" will take place in room 259.


Freitag
Die Arbeitskonferenz “Künstliche Intelligenz Entwicklung für ein widerstandsfähiges und nachhaltiges Morgen” (AI Tomorrow) bringt Forscher:innen im Ratsplenarsaal zusammen, um die ökologischen, sozialen und wirtschaftlichen Auswirkungen des Designs, der Entwicklung und des Einsatzes von KI in der Industrie 5.0 wissenschaftlich zu diskutieren. 

Friday
The working conference on "Artificial Intelligence Development for a Resilient and Sustainable Tomorrow" (AI Tomorrow) brings together researchers in the Ratsplenarsaal (council plenary room) to discuss the environmental, social and economic implications of the design, development and deployment of AI in Industry 5.0.
