### ISSUE TITLE
change LODH event description

### ISSUE THREAD

**Issue by JuliaHolze** [AKSW/leipzig.dataweek.de#134]
### Leipzig Open Data Hackathon 2023

Getreu dem Motto „Daten befreien“ findet in diesem Jahr der „Leipzig Open Data Hackathon“ statt. Hier sollen innovative Ideen entwickelt werden, um städtische Daten schneller und effektiver zu den Menschen zu bringen. 
Interessierte Bürger/-innen, Studierende, IT-Begeisterte und Open-Data-Enthusiasten sind eingeladen, das bestehende Angebot des [Leipziger Open-Data-Portals](https://opendata.leipzig.de/) mit eigenen Ideen und Anregungen noch besser zu machen. Pro Thema wird es für die jeweiligen Gewinnerteams eine Prämie in Höhe von 700 € (1. Platz), 500 € (2. Platz) und 250 € (3. Platz) geben.
### Themen
* Künstliche Intelligenz für die Stadtentwicklung: Für die Stadt Leipzig sind bereits zahlreiche Datenbestände zu vielfältigen Themen wie [Bildung](https://statistik.leipzig.de/statcity/intro.aspx?cat=5&obj=0), [Verkehr](https://statistik.leipzig.de/statcity/intro.aspx?cat=10&obj=0) und [Wirtschaft](https://statistik.leipzig.de/statdist/intro.aspx?cat=8&obj=0) öffentlich verfügbar. Ziel ist es, diese Daten mithilfe intelligenter Verfahren (z.B. Clustering oder Klassifikationsalgorithmen) zu analysieren, damit spannende Erkenntnisse für die künftige Entwicklung der Stadt Leipzig gewonnen werden können.
* Straßen-Quiz: Welche Leipziger Straßen sind nach berühmten Persönlichkeiten benannt? Welche Baumarten des Leipziger Auwaldes sind Namensgeber für Straßen? Der offene Datensatz [Straßennamensverzeichnis mit Erläuterungen](https://opendata.leipzig.de/dataset/strassennamensverzeichnis) enthält Informationen zu den Namen aller über 3.000 benannten Straßen und Plätze der Stadt Leipzig. Dieser Datensatz soll so aufbereitet werden, dass darin enthaltene Informationen besser nutzbar gemacht werden können, z.B. für den Einsatz in einem Quiz zu Leipziger Straßennamen.
* Optimierung Open-Data-Portal: Das Open-Data-Portal Leipzig wird mithilfe der [Open-Source-Software CKAN](https://ckan.org/) betrieben. Zusätzliche Funktionalitäten, wie z.B. Datensatz-Empfehlungen oder Suchwortvorschläge werden mithilfe von Python-Plugins realisiert. Ziel des Projektes ist es, ein CKAN-Plugin zu entwickeln, das die Bedienung des Leipziger Datenportals leichter macht. 
* Offenes Thema: Auf Wunsch können Beiträge rund um das Thema „Daten befreien“ eingereicht werden. Unterschiedliche Ansätze und Themen sind willkommen. Im Fall der Wahl eines offenen Themas bitten wir um eine Kurzzusammenfassung des Vorhabens (ca. 150 Wörter) bei Anmeldung. 

### Anmeldung und Ablauf 
Die Themen können als Einzel- oder Gruppenprojekte in Eigenregie durchgeführt werden. Die Anmeldung für den Leipzig Open Data Hackathon 2023 ist ab sofort und noch bis Ende April 2023 über opendata[at]leipzig.de möglich. Bitte geben Sie bei der Anmeldung Name(n), E-Mail-Adresse(n) und das gewünschte Thema an. Die Ergebnisse sollen auf der Data Week 2023 (Poster & Vortrag) präsentiert und anschließend unter einer Open-Source-Lizenz auf [Open CoDE](https://opencode.de/de) veröffentlicht werden.
    * Anmeldung: 01.02.2023-30.04.2023
    * Einreichungsfrist Poster: 11.06.2023 
    * Präsentation & Preisverleihung Data Week: 27.06.2023
    
Nähere Informationen erhalten Sie vom [Amt für Statistik und Wahlen](https://www.leipzig.de/buergerservice-und-verwaltung/aemter-und-behoerdengaenge/behoerden-und-dienstleistungen/dienststelle/statistik-und-wahlen-amt-fuer-12) der Stadt Leipzig. Anfragen können an opendata[at]leipzig.de gerichtet werden.

### Leipzig Open Data Hackathon 2023

The "Leipzig Open Data Hackathon" will take place this year, true to the motto "Free data!". Participants will develop innovative ideas to bring urban data to the public faster and more effectively. 
We invite interested citizens, students, IT enthusiasts and open data enthusiasts to make the existing offering of [Leipzig Open-Data-Portals](https://opendata.leipzig.de/) even better with their own ideas and suggestions. For each topic, there will be a prize of €700 (1st place), €500 (2nd place) and €250 (3rd place) for the respective winning teams.

### Topics
* Artificial intelligence for urban development: Numerous datasets are already publicly available on a wide range of topics concerning the city of Leipzig including [education](https://statistik.leipzig.de/statcity/intro.aspx?cat=5&obj=0), [transportation](https://statistik.leipzig.de/statcity/intro.aspx?cat=10&obj=0) and the [economy](https://statistik.leipzig.de/statdist/intro.aspx?cat=8&obj=0). The goal is to analyze this data using algorithms (e.g. clustering or classification) so that exciting insights can be gained for the future development of the city of Leipzig.
* Street quiz: Which Leipzig streets have been named after famous personalities? Which tree species of the riverside forest in Leipzig (Leipziger Auwald) have lent their names to city streets? The open dataset "[Straßennamensverzeichnis mit Erläuterungen](https://opendata.leipzig.de/dataset/strassennamensverzeichnis)" contains information on the names of more than 3,000 named streets and squares in the city of Leipzig. This dataset should be prepared in such a way that information contained in it can be made more readily usable, e.g. for use in a quiz on Leipzig street names.
* Improving the Open Data Portal: The Open Data Portal Leipzig is powered by the [open source software CKAN](https://ckan.org/). Additional functionalities, such as dataset recommendations or suggested search terms, are realized with the help of Python plug-ins. The goal of the project is to develop a CKAN plugin that makes the Open-Data-Portal easier to use.
* Open topic: If desired, contributions around the topic "Free data!" can be submitted. Different approaches and topics are welcome. If an open topic is chosen, we ask for a short summary of the project (approx. 150 words) upon registration.

### Registration and procedure 
Individuals or groups can work on the topics autonomously. Registration for the Leipzig Open Data Hackathon 2023 is open from now on and until the end of April 2023 via opendata[at]leipzig.de. Please provide name(s), email address(es) and the chosen topic when registering. The results will be presented at Data Week 2023 (poster & talk) and are subsequently published under an open source license on [Open CoDE](https://opencode.de/de).

* Registration: 01.02.2023-30.04.2023
* Poster submission deadline: 11.06.2023
* Presentation & Award Ceremony Data Week: 27.06.2023.

For more information, please contact the [Amt für Statistik und Wahlen](https://www.leipzig.de/buergerservice-und-verwaltung/aemter-und-behoerdengaenge/behoerden-und-dienstleistungen/dienststelle/statistik-und-wahlen-amt-fuer-12) Leipzig. Any inquiries can be directed to opendata[at]leipzig.de.

**Comment by TBoonX** [comment]
So ich habe die event.ttl aktualisiert. Vorher war deutsch und englisch in einer englischen description
