### ISSUE TITLE
Add events page

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#136]
Since the https://2023.dataweek.de/eid-2023/ is renamed to https://2023.dataweek.de/egd-2023/ now old links that were supposed to direct to the events overview are broken now/in a view minutes. E.g. linked from here https://twitter.com/DataWeekLeipzig/status/1625814678663307265
This make the need for a general events overview resource apparent.

@seebi hat some specific ideas on how this resource/page should look like

**Comment by seebi** [comment]
Vorschlag 1:

<img width="1146" alt="Screenshot 2023-02-20 at 14 53 06" src="https://user-images.githubusercontent.com/510452/220126377-0679cf73-5ae0-49c4-9332-f35c64cf9fba.png">

**Comment by seebi** [comment]
@white-gecko I used [schema:abstract](https://schema.org/abstract) since this property was already in use ...

**Comment by white-gecko** [comment]
A first preview is here: https://staging.dataweek.de/events.html but it still requires a nice layout as of #137 and maybe also in other parts (padding, date highlight, nice title, in general spaces).

**Comment by dannyotto** [comment]
https://prototype.pixelbrand.co/dataweek/sprecher.html

Looks like this without the picture and the bottom part wrapt in `<small>`.

**Comment by white-gecko** [comment]
looks like this now:

![image](https://user-images.githubusercontent.com/1018168/220157142-0491bfaf-5aa3-4f3f-863e-58ef21d8a1ac.png)


@JuliaHolze @seebi any comments?

**Comment by white-gecko** [comment]
I would like to have some subtitle option, then we could but the slug (LSWT and co) to the top and put the full name of the event as subtitle below it.
Also the date should be orange as everywhere on the page.
The abstract should be either left aligned or even better in a justified paragraph.

**Comment by JuliaHolze** [comment]
Hi @white-gecko, your draft looks really good :) 
Subtitle --> Yes
Orange colour --> Yes
justified paragraph --> Yes

**Comment by white-gecko** [comment]
According to the explanation in https://github.com/AKSW/leipzig.dataweek.de/issues/137#issuecomment-1437188256 this requires customization by @dannyotto .

@dannyotto can you help us to get https://github.com/AKSW/leipzig.dataweek.de/issues/136#issuecomment-1437270480 going and see a version in one and in two columns (mybe if the style work out great it could fit in 4 columns ?)

**Comment by dannyotto** [comment]
@white-gecko I have added a cards demo page. You can have a look. If you need more options or elements, let me know.

**Comment by white-gecko** [comment]
Now it looks like this: https://staging.dataweek.de/events.html
![image](https://user-images.githubusercontent.com/1018168/220895912-5a36fb16-d564-4fb6-a25b-fd8d9006701a.png)

I chose to use three columns and have put the long title of the events in `<strong>` tags. Is there some subtitle tag tha we can use @dannyotto ?
Can you setup the justified paragraphs to also apply word wrapping? (I hope we have set the languages in the head correctly for English and German)

**Comment by white-gecko** [comment]
For the reference, this is how it would look like in two columns

![image](https://user-images.githubusercontent.com/1018168/220896659-9535ca78-8615-4b5e-b315-07f33353ee5e.png)
