### ISSUE TITLE
Grid system does not break

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#137]
I'm now using the grid system to put some cards in a two column layout (to implement #136 ) but the grid elements flow over the row. I would have expected elements to go to the next row once the limit is reached. like in:

https://getbootstrap.com/docs/5.2/layout/grid/#row-columns

![image](https://user-images.githubusercontent.com/1018168/220134863-11f7a91f-18ad-4f5e-a70a-284294d614b6.png)

```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.2/assets/css/docs.css" rel="stylesheet">
    <title>Bootstrap Example</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  </head>
  <body class="p-3 m-0 border-0 bd-example bd-example-row">

    <!-- Example Code -->
    
    <div class="container text-center">
      <div class="row row-cols-2">
        <div class="col">Column</div>
        <div class="col">Column</div>
        <div class="col">Column</div>
        <div class="col">Column</div>
      </div>
    </div>
    
    <!-- End Example Code -->
  </body>
</html>
```

**Comment by white-gecko** [comment]
Also I don't find a way to break a row, do I need to start a new grid for each row?

**Comment by dannyotto** [comment]
Currently, the .grid system is only for columns and you have to start a new grid for each row.

If I have to organize a list in columns multiple rows, I use unordered lists with customized css. Customized because I often change the number of columns depending on the screen width. Like in this example:
https://prototype.pixelbrand.co/dataweek/sprecher.html

Can you maybe reuse the contact cards?

**Comment by white-gecko** [comment]
if the contact cards support two column layout? That actually was our inspiration.

**Comment by dannyotto** [comment]
The contact list uses 2 columns on medium screens and 3 columns on normal screens.

**Comment by white-gecko** [comment]
Thank you, the new cards solve the issue.
