### ISSUE TITLE
Improve typography of events overview

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#142]
Follow up to #136.

To improve the events page there are two points (@dannyotto):
- Is there some subtitle tag that we can use? Do you have other suggestions to have a nicer typography of the title and the slug? Currently "EU Green Deal Data Space (EGD)" looks somehow technical. I would prefer some way that we have both sitting on their own line but typed differently.
- Can you setup the justified paragraphs to also apply word wrapping? (I hope we have set the languages in the head correctly for English and German)

**Comment by dannyotto** [comment]
Do you like this title? https://prototype.pixelbrand.co/dataweek/demo/cards.html

I also added word wrapping to the .justify class. Because I've always avoided justify, I didn't even know about the new word wrapping functions. :)

**Comment by white-gecko** [comment]
Thank you.
