### ISSUE TITLE
Add Venue/Hotel page

### ISSUE THREAD

**Issue by JuliaHolze** [AKSW/leipzig.dataweek.de#143]
We need a page to present information about recommended hotels.

**Comment by JuliaHolze** [comment]
<b style="font-weight:normal;" id="docs-internal-guid-ab195516-7fff-7ba0-1d53-2f84eb298b5c"><h2 dir="ltr" style="line-height:1.656;margin-top:18pt;margin-bottom:6pt;"><span style="font-size:16pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Recommended Hotels</span></h2><br /><div dir="ltr" style="margin-left:0pt;" align="left">

Hotel | Address | Get a reduced rate until May 28, 2023
-- | -- | --
Motel One Leipzig-Augustusplatz | Ritterstrasse 4 04109 Leipzig phone: +49 (0)341 2527980 leipzig-augustusplatz@motel-one.com | To get a reduced rate, please write an email to dataweek@infai.org.
Motel One Leipzig-Post | Grimmaischer Steinweg 1 04103 Leipzig phone: +49 (0)341 9621050 leipzig-post@motel-one.com |  
B&B Hotel Leipzig-City | Nikolaistraße 34 04109 Leipzig phone:+49 (0) 341 215800 leipzig-city@hotelbb.com | To get a reduced rate, please write an email to dataweek@infai.org.
NH hotel Leipzig Zentrum | Burgplatz 5 04109 Leipzig phone: +49 (0)341 
HYPERION Hotel Leipzig | Sachsenseite 7 04103 Leipzig phone: +49 (0)341 550020 hyperion.leipzig@h-hotels.com |  
H2 Hotel Leipzig | Sachsenseite 5 04103 Leipzig+49 (0)341 442400 H2.Leipzig@h-hotels.com |  
Travel24 Hotel | Tröndlinring 9 04105 Leipzig phone: +49 (0) 341 33173850 reservierung@hotel-travel24.com |  
Royal International | Richard-Wagner-Straße 10 04109 Leipzig phone: +49 (0) 3412310060 kontakt@royal-leipzig.de |  

<b style="font-weight:normal;" id="docs-internal-guid-ddaa2647-7fff-d339-0e84-5d7b9386d58a"><h2 dir="ltr" style="line-height:1.656;margin-top:18pt;margin-bottom:6pt;"><span style="font-size:16pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Low-price accommodation</span></h2><br /><div dir="ltr" style="margin-left:0pt;" align="left">

Hotel | Address
-- | --
A&O City Hauptbahnhof | Brandenburger Strasse 204103 Leipzigphone: +49 (0) 30 809475000
Five Elements Hostel Leipzig | Kleine Fleischergasse 804109 Leipzigphone: +49 (0) 341 35583196 leipzig@5elementshostel.de
Ibis Budget | Reichsstraße 1904109 Leipzigphone: +49 (0) 341 14939420 H8000@accor.com

**Comment by JuliaHolze** [comment]
<b style="font-weight:normal;" id="docs-internal-guid-47c9e0bb-7fff-9bf6-0e95-a5df6a432a78"><h2 dir="ltr" style="line-height:1.38;margin-top:18pt;margin-bottom:6pt;"><span style="font-size:16pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Empfohlene Hotels</span></h2><br /><div dir="ltr" style="margin-left:0pt;" align="left">

Hotel | Addresse | Erhalten Sie einen ermäßigten Tarif bis 28. Mai 2023
-- | -- | --
Motel One Leipzig-Augustusplatz | Ritterstrasse 4 04109 Leipzig Telefon: +49 (0)341 252798 0leipzig-augustusplatz@motel-one.com | Um einen ermäßigten Tarif zu erhalten, schreiben Sie bitte eine E-Mail an dataweek@infai.org.
Motel One Leipzig-Post | Grimmaischer Steinweg 1 04103 Leipzig Telefon: +49 (0)3419621050 leipzig-post@motel-one.com |  
B&B Hotel Leipzig-City | Nikolaistraße 3 404109 Leipzig Telefon: +49 (0) 341 215800 leipzig-city@hotelbb.com | Um einen ermäßigten Tarif zu erhalten, schreiben Sie bitte eine E-Mail an dataweek@infai.org.
NH Hotel Leipzig zentrum | Burgplatz 5 04109 Leipzig Telefon: +49 (0)341 450800
HYPERION Hotel Leipzig | Sachsenseite 7 04103 Leipzig Telefon: +49 (0)341 550020 hyperion.leipzig@h-hotels.com |  
H2 Hotel Leipzig | Sachsenseite 5 04103 Leipzig Telefon: +49 (0)341 442400 H2.Leipzig@h-hotels.com |  
Travel24 Hotel | Tröndlinring 904105 Leipzig Telefon: +49 (0) 341 3317 3850 reservierung@hotel-travel24.com |  
Royal International | Richard-Wagner-Straße 1 0 04109 Leipzig Telefon: +49 (0) 3412310060 kontakt@royal-leipzig.de |  

<b style="font-weight:normal;" id="docs-internal-guid-9516ebe8-7fff-73da-f222-4b94bcdf3759"><h2 dir="ltr" style="line-height:1.656;margin-top:18pt;margin-bottom:6pt;"><span style="font-size:16pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Preisgünstige Unterkunft</span></h2><br /><div dir="ltr" style="margin-left:0pt;" align="left">

Hotel | Addresse
-- | --
A&O City Hauptbahnhof | Brandenburger Strasse 2 04103 Leipzig Telefon: +49 (0) 30 809475000
Five Elements Hostel Leipzig | Kleine Fleischergasse 8 04109 Leipzig Telefon: +49 (0) 341 35583196 leipzig@5elementshostel.de
Ibis Budget | Reichsstraße 1 904109 Leipzig Telefon: +49 (0) 341 14939420 H8000@accor.com

**Comment by seebi** [comment]
@white-gecko data and template is prepare - pls merge and fix capitalization
