### ISSUE TITLE
change AI-T event date

### ISSUE THREAD

**Issue by JuliaHolze** [AKSW/leipzig.dataweek.de#145]
2023-06-29 - 2023-06-30

**Comment by splattater** [comment]
@JuliaHolze, I think you want the events page to show start and end date if they are given?
The event is currently from 29th - 30th in our data model.
![Bildschirmfoto vom 2023-02-27 12-28-36](https://user-images.githubusercontent.com/1556061/221552981-705254b8-8bac-4327-adf2-9791662137b6.png)

**Comment by JuliaHolze** [comment]
@splattater It would be nice to see the correct date also here: https://2023.dataweek.de/ai-tomorrow-2023/

**Comment by white-gecko** [comment]
As I understand this this fixed.
