### ISSUE TITLE
Please change Scads event dates

### ISSUE THREAD

**Issue by JuliaHolze** [AKSW/leipzig.dataweek.de#148]
Scads decided to organize their trainings on Monday, Wednesday an Thursday. Please change dates on the website. 
![Selection_999(148)](https://user-images.githubusercontent.com/16899957/222140442-06275222-5a43-44e0-aef8-81b29ec2cd99.png)
![Selection_999(149)](https://user-images.githubusercontent.com/16899957/222140550-476061a6-73e7-4056-85a6-826a410987bf.png)

**Comment by splattater** [comment]
Changed in model. Should be online in a few minutes.
