### ISSUE TITLE
Change EGD 

### ISSUE THREAD

**Issue by nilshempelmann** [AKSW/leipzig.dataweek.de#150]
Change abreviation EGD to GDDS (Green Deal data Space)

Change of picture (Nils Hempelmann) to logos 
![OGC_Logo_2D_Blue_x_0_0-2](https://user-images.githubusercontent.com/8639658/222388854-343802fe-5ce9-4c6b-a7a1-d2915c29a715.png)
![GeoE3_bright_final](https://user-images.githubusercontent.com/8639658/222389662-e54c8a16-059f-45f2-9514-9c011ce0ca48.jpg)

Link the logos with 
https://www.ogc.org 
https://geoe3.eu

**Comment by splattater** [comment]
- [x] Change abreviation EGD to GDDS (Green Deal data Space)
- [x] update picture OGC
- [x] add organization and picture for GEOE3, link from person to GEOE3 organization

**Comment by white-gecko** [comment]
> Hier https://staging.dataweek.de/en/gdds-2023/ sollten nur die Logos sein, kein Bild von mir. ;-) . Vielleicht habe ich das nicht gut beschrieben im Issue.

**Comment by splattater** [comment]
I think everything is done now.
A discussion issue #172 was created to find a better solution for the handling of the h3-heading in oragnizerTeam.html
