### ISSUE TITLE
Lightbox does not work

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#151]
The lightbox feature does not work:

I have used the code as given in the demo
```
<a href="files/lightbox.jpg" title="Bildtitel" data-lightbox data-alt="Alternativtext in Großansicht" data-description="Beschreibung">
  <img src="" alt="Großansicht + Kurzbeschreibung"/>
</a>
```
but the lightbox does not work at: https://staging.dataweek.de/venue/

What did I do wrong?

**Comment by dannyotto** [comment]
The image has to be inside of `<div class="image lightbox">`.

**Comment by white-gecko** [comment]
Thanks.
