### ISSUE TITLE
One-line Tab layout

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#153]
We are using the tab menu for the venue navigation now. But since we only have a one line tab title the navigation does not look that cool.

![image](https://user-images.githubusercontent.com/1018168/222398259-f2215dd5-b074-41b2-9382-b94c873dc8fb.png)

@dannyotto do you have an idea how to improve the layout?

**Comment by dannyotto** [comment]
I had to think about it and I have a solution. Please update the css files.

**Comment by white-gecko** [comment]
For the documentation, the difference is now:

before:
![image](https://user-images.githubusercontent.com/1018168/223178584-8007f74c-fcf7-41d7-b5d2-d991c8217980.png)

after:
![image](https://user-images.githubusercontent.com/1018168/223178529-a6104bc7-d8e5-4363-8b4b-575142ffd044.png)

I like it, so I will close the issue. @seebi if you have any additions, please reopen the issue.
