### ISSUE TITLE
Add the LSWT Keynote to the table

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#158]
In order to put the lswt keynote on the webpage already, please fill in the respective line in the lswt program in the table already.

**Comment by JuliaHolze** [comment]
I've added the respective line.

**Comment by white-gecko** [comment]
@JuliaHolze could you please translate the bio for Felix to German?

**Comment by white-gecko** [comment]
Added in 78a85a15e1f99e5ae861967977c7ce1af6ca95d4
