### ISSUE TITLE
Helper include for conjunctive lists

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#164]
In some places we need lists like "Mon, Thu & Fri" and "Person A, Person B, and Person C" or  "Person A, Person B und Person C" (mind the serial comma in the English version!). This includes some bloated code as seen in the following example but does not involve all of the logic necessary for the examples above.

https://github.com/AKSW/leipzig.dataweek.de/blob/95a34a2447fb73b7114c9cbc7f600d323c92e099/_includes/components/menu_events.html#L48-L57

Implement an include that can be used as helper somehow like this:

```
{% include conjunct_list.html list=list conjunction="&" %}
- (de) -> Mo, Di & Fr
- (en) -> Mon, Thu & Fri

{% include conjunct_list.html list=list conjunction=str_and %}
- (de) -> Mo, Di und Fr
- (en) -> Mon, Thu, and Fri
```

**Hint:** check out https://shopify.github.io/liquid/tags/iteration/#forloop-object

**Comment by white-gecko** [comment]
This an implementation in 5dd75f9798bfebb33dd39f82b0261d444fb762fb

**Comment by white-gecko** [comment]
Very nice.

lets call it: `resource_list_inline` or `list_inline`
```
{% include components/list_inline.html sub=session pred="schema:performer" %}
{% include components/list_inline.html sub=session pred="schema:performer" variant="literal" %}
{% include components/list_inline.html sub=session pred="schema:performer" variant="date" format="%a" %}
```

**Comment by white-gecko** [comment]
Further snippets:

to have a fallback for no language tag
```
{%- assign CEURTITLE = paper.entity | rdf_property: "dct:title", site.language -%}
{%- unless CEURTITLE -%}
{%- assign CEURTITLE = paper.entity | rdf_property: "dct:title" -%}
{%- endunless -%}
```

for containers, collections, and multiple objects
```
{%- assign authors = paper.entity | rdf_container: "schema:performer" -%}
{%- unless authors.first -%}
{%- assign authors = paper.entity | rdf_property: "schema:performer" | rdf_collection -%}
{%- endunless -%}
{%- unless authors.first -%}
{%- assign authors = paper.entity | rdf_property: "schema:performer", nil, true -%}
{%- endunless -%}
```

**Comment by splattater** [comment]
I think I will name it literal_list_inline since the solution of #165 should be the resource_list_inline

**Comment by white-gecko** [comment]
No, I thought it will be the same list and it will be the solution of #165 all together.

**Comment by splattater** [comment]
OK, so the default should be the resource variant using the label component?

**Comment by white-gecko** [comment]
@splattater what is missing for this issue to be closed?

**Comment by splattater** [comment]
Nothing, I think
