### ISSUE TITLE
Support for multiple performers

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#165]
In the program currently only one performer is displayed, but we need support for multiple performers.

- [x] check last years code and model
- [x] see if resp. how ordered lists of performers were done
- [x] implement it accordingly
- [x] use some helper as in #164

**Comment by splattater** [comment]
I added a component that creates a string of object resource labels for a given subject and a predicate using the labels component.

**Comment by white-gecko** [comment]
> I added a component that creates a string of object resource labels for a given subject and a predicate using the labels component.

@splattater Would this be the solution for #164 ?

**Comment by splattater** [comment]
Maybe we can add a third param for an option how to serialize the values.
Label, dates and plain could be the values?
Also I plan to add a second component for literals.

**Comment by splattater** [comment]
I will close this issue. We can use #164 for the ongoing discussion.
