### ISSUE TITLE
Add photo and bio to program for keynotes

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#166]
So far a keynote looks like this:
![image](https://user-images.githubusercontent.com/1018168/223373371-ed315cd6-da30-47a4-b1a7-ff7b88b11ae4.png)

Last year we had a space for the bio and photo of the keynoter to prominently advertise the keynotes.

How can we do this with the current layout, do we need changes?

![image](https://user-images.githubusercontent.com/1018168/223372461-6c663448-8374-49db-a13e-f2b19d9b1b75.png)

**Comment by dannyotto** [comment]
https://prototype.pixelbrand.co/dataweek/programm_montag_bereich-a.html

What do you think?

**Comment by white-gecko** [comment]
Thank you very much. I have implemented it in the template:


![Image](https://user-images.githubusercontent.com/1018168/226914513-7f814ae5-3b35-4baf-852b-3982df82c64d.png)
