### ISSUE TITLE
Add the possibility to also make non persons the organizers of an event

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#168]
The gdds is organized by OGC and GEOE3 rather then individual persons.
We need the possibility to also make non persons the organizers of an event.

E.g. `foaf:Agent`

**Comment by splattater** [comment]
Commit https://github.com/AKSW/leipzig.dataweek.de/commit/46f3fba91a2e548dacab791784bb85ae238d2469 solves this issue. schema:Organization can be used as organization team members, too from know on.
