### ISSUE TITLE
organizerTeam.html make heading optional

### ISSUE THREAD

**Issue by splattater** [AKSW/leipzig.dataweek.de#172]
At the moment we set a header for organizational team (rdfs:label or fallback string).

![Bildschirmfoto vom 2023-03-15 13-23-21](https://user-images.githubusercontent.com/1556061/225307970-6412ada1-5a71-42a8-8b25-632811a2e5b4.png)

With the introduction of organizations as a organizational team member the wish came up to remove the heading.
I committed a quick hack that suits the actual template but is not a good practice: https://github.com/AKSW/leipzig.dataweek.de-model/commit/1ed108eab0a619c504bb20a30726005703b38d06
![Bildschirmfoto vom 2023-03-15 13-26-13](https://user-images.githubusercontent.com/1556061/225308549-4d359371-727a-451d-bf63-f12b928e7b0f.png)

Do we want to 
- remove the fallback heading and allow teams without labels or
- do we want to add another statement like dw:showHeading True/False to control the heading or
- do we want to keep the hack or
- ...?

**Comment by white-gecko** [comment]
Please implement the first option "remove the fallback heading and allow teams without labels or" so we will only display a heading if a label is explicitly set for the team.

**Comment by white-gecko** [comment]
@splattater Is this implemented as commented in https://github.com/AKSW/leipzig.dataweek.de/issues/172#issuecomment-1471723099 ?
