### ISSUE TITLE
Program missing affiliation 

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#173]
@JuliaHolze can you please explain the issue further

**Comment by JuliaHolze** [comment]
The affiliations are missing in the program draft (GDDS). Please add them.

**Comment by JuliaHolze** [comment]
![Selection_999(154)](https://user-images.githubusercontent.com/16899957/225616814-3d6bb09a-18a7-4728-a70b-4c81e4fd50da.png)

**Comment by splattater** [comment]
- [x] added a new component
- [x] applied component for session and talks
- [ ] TODO: remove leading space in brackets
- [ ] TODO: make component variable regarding second predicate
- [ ] TODO: fix if-statement so brackets won't appear if no objects of second step were found

**Comment by splattater** [comment]
I will create a new issue for the last TODO since it is more related to the component than to the affiliation issue.
The affiliation issue should be solved by now.
