### ISSUE TITLE
Week overview table

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#175]
Hey @dannyotto would it be possible to extend the layout to also work for three parallel sessions?

currently it is in the layout:
![image](https://user-images.githubusercontent.com/1018168/225592895-30619897-7601-4302-a30d-e3335f5f1d93.png)

but we also have at least one slot with three parallel sessions, in this case the three workshops do not appear to have a lot of content text so it should work:

![image](https://user-images.githubusercontent.com/1018168/225594310-71f72685-9087-4b74-bc5c-af285111497e.png)

@JuliaHolze will clarify if also in the 14.00 case the parallel sessions will have not to much content text.

![image](https://user-images.githubusercontent.com/1018168/225594489-6c8552ac-05d0-4042-83b5-74562bf15435.png)

**Comment by nilshempelmann** [comment]
All five rooms are most of the time all filled with some session. 
We need urgently an agenda were all parallel sessions on all rooms are visible! 

The above example is also a workshop form in 'Ratsplenarsaal' which is not visible in the current organization of the event. 

Please organise the Agenda ordered by days and rooms.

**Comment by dannyotto** [comment]
Can someone please prepare me a sample day with all the parallel sessions and needed information?

5 parallel sessions are probably not possible with the current solution.

**Comment by nilshempelmann** [comment]
@dannyotto : here you find all sessions all days: https://msinfai.sharepoint.com/:x:/s/DataWeek2022/Efc0I5IGmhZHjWJ4_LQB6SMB93fwTavpkiiYgCMHoOWyzg?email=nhempelmann%40ogc.org&e=4%3A7K9dur&at=9 @JuliaHolze will give you the access rights.

**Comment by dannyotto** [comment]
What do you think about this version? Are there any change requests?

https://prototype.pixelbrand.co/dataweek/programm_montag.html

**Comment by JuliaHolze** [comment]
The program overview looks good. Please remove the subheading/description. I would like to keep it clean and simple. @dannyotto Do we need to display the time twice? If not, please remove the time (orange), it is already in blue above the line.

**Comment by dannyotto** [comment]
Yesterday Natanael told us there are sessions with different durations so he need the time information twice. But they can also be omitted in the implementation.

**Comment by white-gecko** [comment]
@dannyotto the column width varies based on the amount of text. We need a fixed width of the columns. Is this possible?

![image](https://user-images.githubusercontent.com/1018168/228801170-d36f96a0-3bf8-44b7-af7c-e9a61d909c82.png)

**Comment by dannyotto** [comment]
Can you please add `style="width=20%"` in every `<th>` of table thead tr ?

`<th style="width=20%"></th>`

So you can adjust the width depending on the amount of columns.

**Comment by white-gecko** [comment]
Yes that works. Thank you.
