### ISSUE TITLE
Please add news post

### ISSUE THREAD

**Issue by JuliaHolze** [AKSW/leipzig.dataweek.de#178]
Please add the second news post.

### Data Week Leipzig - June 26th to June 30th
Mark your calendars for Data Week Leipzig 2023 and join us from June 26th to June 30th, for a week of learning, networking and innovation. Discover scientific experts' latest trends and advancements in data and AI and take part in interactive workshops and trainings, hear inspiring keynote speeches and connect with fellow professionals. Data Week Leipzig unites individual event formats in the field of research and transfer, which are organized by the participating scientific and transfer institutions Institute for Applied Informatics. and ScaDS.AI Dresden/ Leipzig, as well as eccenca GmbH, the DBpedia Association, and the AKSW network. This year's program is already in development and will soon be published on our new website.

### Data Week Leipzig - 26. Juni bis 30. Juni
Merken Sie sich die Data Week Leipzig 2023 in Ihrem Kalender vor und nehmen Sie vom 26. bis 30. Juni an einer Woche voller Lernen, Vernetzung und Innovation teil! Sie können interaktive Workshops und Schulungen besuchen, inspirierende Keynotes hören und sich mit anderen Fachleuten und Wissenschaftler:innen zu neuesten Trends und Forschungsergebnisse im Bereich Daten und KI austauschen. Die Data Week Leipzig vereint einzelne Veranstaltungsformate im Bereich Forschung und Transfer, die von den beteiligten Wissenschafts- und Transfereinrichtungen Institut für Angewandte Informatik und ScaDS.AI Dresden/ Leipzig sowie der eccenca GmbH, dem Verein DBpedia und dem AKSW-Netzwerk organisiert werden. Das diesjährige Programm ist bereits in Arbeit und wird in Kürze auf unserer neuen Website veröffentlicht.

**Comment by white-gecko** [comment]
@TBoonX can you please publish this post in the same way as the first post?

**Comment by TBoonX** [comment]
Done
