### ISSUE TITLE
Adding the InfAI Logo to the Kooperationspartner Panel

### ISSUE THREAD

**Issue by MichaelMartin** [AKSW/leipzig.dataweek.de#181]

**Comment by splattater** [comment]
Adding the logo will result in an (overfull) footer as shown in the first example image.
Please discuss, if we should 
- [ ] remove the heading (second image) or if we should
- [ ] ask @dannyotto for a solution

## full
![Image](https://user-images.githubusercontent.com/1556061/227151446-b34e9e7b-a9ae-4484-a919-48a5cc2cee94.png)

## without heading


![Image](https://user-images.githubusercontent.com/1556061/227153868-33ce5c8f-76e7-4964-b898-b257a272df6f.png)

**Comment by white-gecko** [comment]
Replaced by #185
