### ISSUE TITLE
Clarify organization, co-organization, kooperation and sponsoring/funding logos

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#185]
We will need to restructure the logos of organization, co-organization, cooperation and sponsoring/funding logos.

We will have sections for:

Organizer/Veranstalter: InfAI

Co-Organizers/Mitorganisatoren:
- eccenca
- SCADS
- Open Geospatial Consortium

In cooperation with/In Kooperation mit:
- Stadt Leipzig/Stadt Leipzig Referat Digitale Stadt
- Connected Urban Twins
- KMI
- DBpedia
- AKSW
- GEOE3

Data Week Sponsors/Data Week Sponsoren:
- Funded EU, (eccenca), Stack Fuel, Alexander Thamm, DATEV, edih

Replaces #184 and #181
Will probably also replace #109

**Comment by white-gecko** [comment]
Regarding https://github.com/AKSW/leipzig.dataweek.de/issues/181#issuecomment-1480824643 (cc @splattater)

- [ ] All of the logos should go into the sponsors section.
- [ ] The organizers section on the "Organization Team" page should be removed.
- [ ] The footer bar of logos should be removed.

![Image](https://user-images.githubusercontent.com/1556061/227151446-b34e9e7b-a9ae-4484-a919-48a5cc2cee94.png)

**Comment by splattater** [comment]
the current status is commited in the feature branch
