### ISSUE TITLE
Sub-events logic is very confusing

### ISSUE THREAD

**Issue by nilshempelmann** [AKSW/leipzig.dataweek.de#191]
The separation of the different sessions in sub-events is very confusing. Especially the abbreviations are not consistent, containing 'Free!', event titles: 'LSWT' or thematic topics like green deal 'GDDS'. 

Confusing is also the distribution over time: 
<img width="978" alt="image" src="https://user-images.githubusercontent.com/8639658/227924875-b0de751a-8e16-4323-9675-6d1052ffb0ec.png">

Suggestion: remove the sub-events and mark the sessions in the main program.

**Comment by white-gecko** [comment]
To remove the sub events is a general question that would need discussion with the team. (CC: @seebi @JuliaHolze @MichaelMartin  …)
Regarding the point to mark the sub events as sessions in the program this is our plan anyhow, feel free to create a separate issue for that.

**Comment by nilshempelmann** [comment]
@JuliaHolze @MichaelMartin @white-gecko : 
Maybe it is an option to change 'Events' into 'Topics'. We can slightly adapt the text descriptions of the contributing groups and have a then nice overview of each topic being discussed at the session, room, or day in the program or the sub-programs.

**Comment by JuliaHolze** [comment]
I definitely need a subpage for trainings and tutorials, which should then be found under tracks.

**Comment by JuliaHolze** [comment]
the following tracks should be on the page: Trainings & Tutorials, Leipzig Semantic Web Day and AI-Tomorrow

**Comment by nilshempelmann** [comment]
@JuliaHolze great! Session '[Location Innovation Academy](https://staging.dataweek.de/en/2023-06-27/Ratsplenarsaal.html#17:00)' is a training as well.

**Comment by white-gecko** [comment]
@JuliaHolze Is this issue resolved in the meantime?
Does any new task (new issue) arise regarding the new Trainings track?
