### ISSUE TITLE
No line breaks in the descriptions 

### ISSUE THREAD

**Issue by nilshempelmann** [AKSW/leipzig.dataweek.de#193]
Linebreaks done in the description of the underpinned Excel sheet is not reflected at the web-page

<img width="878" alt="image" src="https://user-images.githubusercontent.com/8639658/227925920-73c05761-ecf6-4e7a-9bb8-59eaf75f5963.png">

In the excel sheet:
<img width="388" alt="image" src="https://user-images.githubusercontent.com/8639658/227926505-8cb7adff-c92b-4957-83c7-75f979c35e18.png">

**Comment by white-gecko** [comment]
The strings are interpreted as markdown where empty line breaks are ignored but empty lines are interpreted as new paragraph.

cf. https://www.markdownguide.org/basic-syntax#paragraphs-1

so please insert new paragraphs where you need them.
