### ISSUE TITLE
Add keynote speakers to front page

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#201]
Please everyone write down thes keynote speakers that should be added to the front page.

**Comment by JuliaHolze** [comment]
Please do not name the section "Keynote Speakers", please use "Highlighted Speakers".

**Comment by NievesECC** [comment]
LSWT Keynote (Mittwoch 28.06.23) Sitzungssaal:  Felix Sasaki, Expert for knowledge graphs and semantic technologies (SAP SE)

**Comment by JuliaHolze** [comment]
Dienstag: 27.06.2023: Clemens Schülke, Bürgermeister und Beigeordneter für Wirtschaft, Arbeit und Digitales (Stadt Leipzig/Dezernat Wirtschaft, Arbeit und Digitales) - Grußwort
Clemens Schülke, Mayor and Councillor for Economic Affairs, Labour and Digital Affairs (City of Leipzig/Department of Economics, Labour and Digital Affairs) -  Welcoming address

**Comment by nilshempelmann** [comment]
Ingo Simonis, Nestor Fernandez, Antti Jacobson und einer von der EU.

**Comment by JuliaHolze** [comment]
Updated list:
26.6.
- Jordi Escriu (urn:url-encoded-value:European+Comission): European policy developments around the Green Deal data space
- Dr. Nestor Fernandez (idiv): European Strategies for biodiversity protection
- Dr. Ingo Simonis (OGC): Technical concepts, options and challenges to achieve Green Deal

27.6.
- Dr. Ingo Simonis (OGC): Datenräume für eine gemeinsame Entwicklung klima-angepasster Städte
- Christian Güthert (EDF Deutschland): Energiewende in der Stadt - Herausforderungen für Netze und Energieversorger
28.6.
- Dr. Felix Sasaki (SAP SE): Große Sprachmodelle, Daten und Wissen: ein positiver Kreislauf

**Comment by nilshempelmann** [comment]
> Updated list: 26.6.
> 
> * Jordi Escriu (urn:url-encoded-value:European+Comission): European policy developments around the Green Deal data space
> * Dr. Nestor Fernandez (idiv): European Strategies for biodiversity protection
> * Dr. Ingo Simonis (OGC): Technical concepts, options and challenges to achieve Green Deal
> 
> 27.6.
> 
> * Dr. Ingo Simonis (OGC): Datenräume für eine gemeinsame Entwicklung klima-angepasster Städte
> * Christian Güthert (EDF Deutschland): Energiewende in der Stadt - Herausforderungen für Netze und Energieversorger
>   28.6.
> * Dr. Felix Sasaki (SAP SE): Große Sprachmodelle, Daten und Wissen: ein positiver Kreislauf

Please also include Antti Jacobsson 26th

**Comment by splattater** [comment]
Keynote slider added to homepage.
Keynotes will be added via pipeline if column in the excel sheet is checked.

**Comment by JuliaHolze** [comment]
@splattater Please add dates in the keynote slider and add Antti Jacobsson.

**Comment by JuliaHolze** [comment]
26.6.

- Antti Jacobsson (GeoE3): Geospatially enabled ecosystem for Europe
