### ISSUE TITLE
Add tickets in menu

### ISSUE THREAD

**Issue by JuliaHolze** [AKSW/leipzig.dataweek.de#202]
Please add a ticket button on the homepage or "tickets" in the menu.

**Comment by white-gecko** [comment]
What should be the content of the new ticket page?
Can you please provide us with the price table and the link to the booking system and so on?

**Comment by JuliaHolze** [comment]
Tagesticket: 85€
Day Ticket: 85€ 
Wochenticket: 400€  
Full Week: 400€
https://pretix.eu/infai/dataweek2023/

**Comment by JuliaHolze** [comment]
Last year we had info on the ticket page that students should email to dataweek@infai.org for a reduced ticket.

**Comment by white-gecko** [comment]
Do we want this information this year as well? Could you please compile all of the information that should go on this new ticket page?

**Comment by JuliaHolze** [comment]
Yes, please add also these info from last year. 
Tages- und Wochentickets können hier erworben werden: https://pretix.eu/infai/dataweek2023/. Sie müssen ein Ticket erwerben um an der Data Week Leipzig teilnehmen zu können. Studierende können sich unter dataweek@infai.org ein vergünstigtes Ticket sichern. Wir stellen ein begrenztes Kontigent bereit. Wir freuen uns auf Ihre Teilnahme!

Daily and weekly tickets can be purchased here: https://pretix.eu/infai/dataweek2023/. You must purchase a ticket to attend Data Week Leipzig. Students can secure a discounted ticket at dataweek@infai.org. We will provide a limited contingent. We look forward to your participation!
