### ISSUE TITLE
Breaks with different titles in spreadsheet will occur in more than one program break unit.

### ISSUE THREAD

**Issue by splattater** [AKSW/leipzig.dataweek.de#206]
Two breaks (same start and end) of two different events with different values in title columns will occur in two break unit entries in program overview (all).
Check all breaks in Spreadsheet and use the same titles (Kaffeepause, Mittagspause) in every event.

**Comment by white-gecko** [comment]
the break resources are merged now but still a homogenization of the title is desirable.
