### ISSUE TITLE
New room overview figure

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#216]
We need an updated room overview figure including all rooms in use.

cf. https://staging.dataweek.de/venue/

**Comment by JuliaHolze** [comment]
![Veranstaltungsplan + Festsaal_EN](https://github.com/AKSW/leipzig.dataweek.de/assets/16899957/1f990aca-637f-4f0e-815e-16e6ec03d04c)
![Veranstaltungsplan + Festsaal](https://github.com/AKSW/leipzig.dataweek.de/assets/16899957/cdbdafc8-87b6-40fd-b772-9f2310594a16)

**Comment by JuliaHolze** [comment]
Room 263 is to the right of the Ratsplenarsaal.
