### ISSUE TITLE
Move Organisation Team into Footer

### ISSUE THREAD

**Issue by nilshempelmann** [AKSW/leipzig.dataweek.de#233]

**Comment by splattater** [comment]
Removed from MainMenu

**Comment by white-gecko** [comment]
Solved with a61cd16cb9a415b27930c4cfe2c655e325634baa, 3dd20e1e66e755f77285f6fabd60346793a73726, and 2eb72cd9d87cef5ae17b9ce5b48e796c6fa7140f
