### ISSUE TITLE
Update ScadsTrainings text

### ISSUE THREAD

**Issue by JuliaHolze** [AKSW/leipzig.dataweek.de#236]
Please update the text about scads trainings here: https://2023.dataweek.de/scads-tutorials-2023/

Im Rahmen der Data Week bietet ScaDS.AI Dresden/Leipzig an drei Tagen Data Science Trainings für interessierte Wissenschaftler:innen, Student:innen und nicht-wissenschaftliche Nutzer:innen an. Dabei werden in den Trainings sowohl technische als auch methodische Schwerpunkte vermittelt: Der technische Schwerpunkt umfasst den Umgang mit Werkzeugen zur Datenanalyse, zum verteilten Rechnen und zum maschinellen Lernen mithilfe der Programmiersprachen R und Python sowie die Anwendung dieser Werkzeuge mit Hilfe von Containern und virtuellen Maschinen. Der methodische Schwerpunkt umfasst die Vermittlung von Methoden der Datenanalyse, der Statistik und des maschinellen Lernens.

Folgende Schulungen werden im Rahmen der Data Week Leipzig 2023 angeboten:

### Montag 26.06.2023: ScaDS.AI Training Datenvisualisierung
Daten sind in der heutigen Wissenschaft und Wirtschaft eine relevante Ressource. Ihre Darstellung in Form von Diagrammen und Plots legt den Grundstein für die Analyse, die Kommunikation sowie die Generierung neuer Hypothesen. Im Kurs werden theoretische Aspekte zusammen mit praktischen Erfahrungen in R unter Verwendung des etablierten Pakets ggplot2 vermittelt. Neben dem Hands-on-Tutorial werden den Teilnehmern typische Probleme bei der Datenvisualisierung, die häufig auftreten und manchmal sogar zur Fehlinterpretation von Daten führen, aufgezeigt.

### Mittwoch, 28.06.2023: ScaDs.AI Training mit der Stadt Leipzig 
Dieses Training ist auf die Bedürfnisse der Mitarbeiter:innen der Stadt Leipzig abgestimmt und legt die Schwerpunkte auf die Vermittlung von Datenkompetenzen - insbesondere zu Datenarten und -strukturen, zu verschiedenen Analyseverfahren und der Nutzung der Programmiersprache Python zur Datenanalyse. Neben theoretischen und praktischen Grundlagen zu allen Aspekten (erster Teil, Vormittag) wird die Datenanalyse mit Python auch an praktischen Beispielen vermittelt (zweiter Teil, Nachmittag). Die Anmeldung steht nur Mitarbeiter:innen der Stadt Leipzig zur Verfügung.

 ### Donnerstag 29.06.2023: ScaDs.AI Training zu den theoretischen Grundlagen von KI/ML

Die Teilnehmer:innenzahl ist auf max. 20 Personen pro Schulung begrenzt. Die Anmeldung erfolgt (außer für das Training mit den Stadtmitarbeiter:innen) beim Kauf der Data Week Leipzig Tickets über das Ticketingsystem.

Englischer Text

 As part of Data Week, ScaDS.AI Dresden/Leipzig is offering three days of Data Science training for interested scientists, students, and especially non-scientific users. Within teaching and training, both technical and methodological priorities are set. The technical focus includes tools for data analysis, distributed computing, and machine learning such as R and Python. On the other hand, the use of tools with the help of containers and virtual machines plays a role. The methodological focus includes instruction in methods of data analysis, statistics, and machine learning. The following trainings are offered as part of the Data Week Leipzig 2023:

### Monday 26.06.2023: ScaDS.AI Training on Data Visualisation

Data is perhaps the most important resource in today’s science and economy. Its representation as graphs and plots is the cornerstone for analysis, communication, and generation of new hypotheses. The course will teach theoretical aspects and practical experience in R using the established package ggplot2. Besides the hands-on tutorial, participants will be shown typical problems in data visualization which frequently occur and sometimes even used to mislead data interpretation.

 ### Wednesday, 28.06.2023: ScaDs.AI Training with the City of Leipzig. 

This training is tailored to the needs of the employees of the City of Leipzig and focuses on teaching data skills - in particular on data types and structures, on various analysis methods and the use of the Python programming language for data analysis. In addition to theoretical and practical basics on all aspects (first part, morning), data analysis with Python will also be taught using practical examples (second part, afternoon). Registration is only available for employees of the city of Leipzig.

### Thursday 29.06.2023: ScaDs.AI Training on the theoretical foundations of AI/ML

The number of participants is limited to a maximum of 20 persons per training. Registration (except for the training with the city employees) takes place when purchasing the Data Week Leipzig tickets via the ticketing system.

**Comment by splattater** [comment]
should i just remove the current text and paste the new text?

**Comment by JuliaHolze** [comment]
Yes, please update the text about the scads tutorials. Info about eccenca and AT trainings remains unchanged on the site.
