### ISSUE TITLE
Trainings & Tutorials

### ISSUE THREAD

**Issue by JuliaHolze** [AKSW/leipzig.dataweek.de#239]
Please add Tuesday on the white tile and change the description text
de: Im Rahmen der Data Week Leipzig finden mehrere Trainings und Tutorials statt und geben Einblick in verschiedene Use Cases und Datensätze.
en: Several trainings and tutorials will take place during Data Week Leipzig and provide insight into different use cases and data sets.
![Selection_999(179)](https://user-images.githubusercontent.com/16899957/236136106-05b4a76e-f9c2-48d9-8cbf-8cb3264bd588.png)

 Futhermore, please add the following text on the t&t page:

 ### Location Innovation Academy on Tuesday, June 27

en: Location Innovation Academy offers 3 courses and 12 e-learning modules to help government agencies, particularly national mapping organizations, make the most of their existing geospatial platforms and create a cloud-based system of generic services that can connect various datasets and services with geospatial data. The session is a training on how to use this online academy

### Location Innovation Academy am Dienstag, 27.06.
de: Die Location Innovation Academy bietet 3 Kurse und 12 E-Learning-Module an, um Regierungsbehörden, insbesondere nationalen Kartierungsorganisationen, dabei zu helfen, ihre bestehenden Geodatenplattformen optimal zu nutzen und ein cloudbasiertes System von Basisdiensten zu schaffen, das verschiedene Datensätze und Dienste mit Geodaten verbinden kann. Die Sitzung ist eine Schulung zur Nutzung dieser Online-Akademie

**Comment by splattater** [comment]
- [x] update abstract
- [x] update description
- [x] add tuesday but not serielized, yet -> investigating
