### ISSUE TITLE
Add Workshop Semantics to LSWT track

### ISSUE THREAD

**Issue by JuliaHolze** [AKSW/leipzig.dataweek.de#281]
Please add infos about the Workshop Semantics https://2023.dataweek.de/2023-06-28/Room259.html#10:15 to the LSWT track on Wednesday. https://2023.dataweek.de/lswt2023/

**Comment by splattater** [comment]
I added all workshops of room 259 (wednesday), right @JuliaHolze?
https://staging.dataweek.de/lswt2023/workshops/

**Comment by white-gecko** [comment]
This should first be discussed with the LSWT team on thursday befor it can be merged.
