### ISSUE TITLE
Add new room 263 in the program

### ISSUE THREAD

**Issue by JuliaHolze** [AKSW/leipzig.dataweek.de#286]
Tuesday program: 

- [x] Please add Festsaal in the program. 2 Sessions (Stadtplanung: Daten interoperabilität im Bauwesen und in der bebauten Umwelt und Stadtplanung: Plattformen für digitale Baugenehmigungen) will take place there on Tuesday.

- [x] Please add the new room 263 in the program. The data spaces: agriculture session and the eccenca training will take place there.

**Comment by splattater** [comment]
Information was added to event model
