### ISSUE TITLE
Pipeline is failing

### ISSUE THREAD

**Issue by splattater** [AKSW/leipzig.dataweek.de#325]
Pipeline does not work
Build Jekyll Page Preview: All jobs have failed
e.g. https://github.com/AKSW/leipzig.dataweek.de/actions/runs/6781233825/job/18431171148

**Comment by splattater** [comment]
I tried it out locally. The pinned logger version (< 1.4.3) of jekyll-rdf 4.1.1 is in conflict with ~>1.5.0 required in jekyll 4.3.2

**Comment by white-gecko** [comment]
If you have tried it locally, you have probably kept an old `Gemfile.lock` which you need to remove first.
