### ISSUE TITLE
Add Nils to the Orga Team

### ISSUE THREAD

**Issue by JuliaHolze** [AKSW/leipzig.dataweek.de#33]
![Nils Hempelmann](https://user-images.githubusercontent.com/16899957/214584302-a247116d-76e0-4a1f-803e-5eaee69de5b9.png)
![Open_Geospatial_Consortium_logo svg](https://user-images.githubusercontent.com/16899957/214584319-0371e4bf-1b0f-491a-8b80-259497ed6b0a.png)
he will organize sessions on monday (26.6) and tuesday (27.6.)

**Comment by splattater** [comment]
Wie heißt Nils denn vollständig?

**Comment by splattater** [comment]
- Image added to develop and next
- Person created in model

**Comment by JuliaHolze** [comment]
> Wie heißt Nils denn vollständig?

Nils Hempelmann

**Comment by splattater** [comment]
Er ist jetzt Teil des MajorProgramChair der Dataweek.
