### ISSUE TITLE
New button "CfP" on the homepage

### ISSUE THREAD

**Issue by JuliaHolze** [AKSW/leipzig.dataweek.de#332]
Please delete "CfP" from the menu and place a button on the homepage after "A data festival for IT enthusiasts! Data Week offers a week-long programme of events on the topics of data, digitalization, artificial intelligence and the challenges of urban development".

**Comment by splattater** [comment]
Ist das die richtige Position für den Button?
![image](https://github.com/AKSW/leipzig.dataweek.de/assets/1556061/352deaf7-431b-4f66-9048-5f05eb69c164)

**Comment by JuliaHolze** [comment]
The second one please.

**Comment by JuliaHolze** [comment]
Can you please write "Ausschreibung" on the German page?
