### ISSUE TITLE
Add the Data Science Mania Team

### ISSUE THREAD

**Issue by JuliaHolze** [AKSW/leipzig.dataweek.de#35]
They will organize the Data Science Mania Event on June 28.
![Christian Rößler](https://user-images.githubusercontent.com/16899957/214585692-66c8f659-1f44-43f7-8591-f21c6030d691.jpeg)
![enrico macholdt](https://user-images.githubusercontent.com/16899957/214585702-58686976-fb4c-41aa-a9bf-2419f25906aa.jpg)
![melanie pufahl](https://user-images.githubusercontent.com/16899957/214585712-a1a95a92-feee-4ea5-a5df-b8e1db2b03f9.jpg)
![Sebastian Boehm](https://user-images.githubusercontent.com/16899957/214585717-f79fb9d6-7ea5-4561-ba9f-51ca3ab1ac5d.jpg)

**Comment by splattater** [comment]
- Images added to next and develop
- foaf:Persons added to model

**Comment by splattater** [comment]
- Team and team members added and linked
