### ISSUE TITLE
Program page

### ISSUE THREAD

**Issue by JuliaHolze** [AKSW/leipzig.dataweek.de#383]
Please create a program page and add all details like in 2023. https://2023.dataweek.de/program.html

**Comment by splattater** [comment]
Montag: Sitzungssaal, Festsaal, Ratsplenarsaal, R259, R260, R270, R495
Dienstag: Sitzungssaal, Festsaal, Ratsplenarsaal, R259, R260, R270, R377
Mittwoch: Sitzungssaal, Festsaal, Ratsplenarsaal, R259, R260, R270, R360, R377, R495
Donnerstag: Sitzungssaal, Festsaal, Ratsplenarsaal, R259, R260, R270, R495, SmartCityLab
Freitag: Sitzungssaal, Festsaal, Ratsplenarsaal, R495
