### ISSUE TITLE
Please add new track tile 2. Leipzig Open Data Hackathon

### ISSUE THREAD

**Issue by JuliaHolze** [AKSW/leipzig.dataweek.de#395]
https://2024.dataweek.de/lodh-2024/
LODH
2. Leipzig Open Data Hackathon
2nd Leipzig Open Data Hackathon

Mo
2024-04-15

Interessierte Bürger/-innen, Studierende, IT-Begeisterte und Open-Data-Enthusiasten sind eingeladen, das bestehende Angebot des Leipziger Open-Data-Portals mit eigenen Ideen und Anregungen noch besser zu machen.
We invite interested citizens, students, IT enthusiasts and open data enthusiasts to make the existing offering of Leipzig Open-Data-Portals even better with their own ideas and suggestions.

# 2. Leipziger Hackathon: Zugang zu Urbanen Datenplattformen für Bürger/-innen ermöglichen 

Unter dem Motto „Zugang zu Urbanen Datenplattformen für Bürger/-innen ermöglichen“ findet in diesem Jahr der 2. Leipzig Hackathon im Rahmen der Data Week statt. Ziel ist es, innovative Konzepte zu entwickeln, um städtische Daten effizienter und schneller zugänglich zu machen. 
Bürgerinnen und Bürger, Studierende, IT-Enthusiasten und Open-Data-Liebhaber sind herzlich eingeladen, die städtischen Anwendungen und Schnittstellen zu den Bürger/-innen mit eigenen Ideen und Vorschlägen zu bereichern. 

**Datum Hackathon:**  12. April - 13. April 2024, **Ort:** Smart City Lab (Magazingasse 3, 04109 Leipzig) 
**Präsentation und Preisverleihung** am 15. April (15:30 - 17:00 Uhr), **Ort:** Neues Rathaus Leipzig 
**Anmeldungen bis zum 01. April über [Digital@Leipzig.de](mailto:Digital@Leipzig.de) 
Bitte geben Sie bei der Anmeldung Name(n), E-Mail-Adresse(n) und das gewünschte Thema an.** 

Themen:  
**1.	**Digitale Karten spielend leicht verstehen lernen**** 
Kartenbasierte Beteiligungsplattformen werden zunehmend in städtischen Planungs- und Entwicklungsvorhaben eingesetzt, um mehr Einwohner/-innen aus unterschiedlichen Zielgruppen zu erreichen. Allerdings bringen diese Herausforderungen mit sich: Einerseits muss man die Anwendung selbst erlernen, was sich über Benutzerführung und Dokumentation erreichen lässt, andererseits müssen die Nutzer/-innen Karten und Geodaten selbstständig lesen, verstehen und verwenden können. Ziel ist es, Werkzeuge oder Ideen zu entwickeln, die diese Hürden überwinden. Wie finden wir eine „leichte Sprache” für Karten- und Geoinformationen? Wie lassen sich abstrakte Konzepte wie Kartenlayer und ihre Zusammenhänge für alle zugänglich machen?  
 
**2.	**Open Data Kataloge erschließen****  
Open Data Portale, wie das Leipziger, nutzen eine Vielzahl von verschiedenen Software-Lösungen, die unterschiedlichste Möglichkeiten anbieten, nach Datensätzen zu suchen und mit ihnen zu interagieren. Häufig sind diese Interfaces nicht barrierefrei oder nur für Expert/-innen zu bedienen, die schon wissen, wonach sie suchen. Für das in Leipzig eingesetzte CKAN wird derzeit auch erwogen, das Frontend grundsätzlich neu zu konzipieren.. 
Open Data konzentriert sich per Definition auf maschinenlesbare Daten, auch bei den veröffentlichten Metadaten-Katalogen. EU-weit veröffentlichen öffentliche Stellen diese nach dem Standard DCAT-AP. In der Regel lassen sie sich über eine einzige URL abrufen, wie auch [der Katalog des Open Data Portals Leipzig](https://opendata.leipzig.de/catalog.ttl). 
Wie kann man diese Kataloge besser zugänglich und durchsuchbar machen? Wie schlägt man eine Brücke von Amts- und Fachsprache zu den Fragen, die die Leipziger Bürger/-innen stellen? Können Assistenzsysteme wie Large Language Models dabei unterstützen? 
 
Wir freuen uns bei Software-Einreichungen besonders über solche, die auf accessible-by-design Frameworks (z.B. [KoliBri](https://public-ui.github.io/)) setzen, oder sich in die existierende Open-Source-Landschaft einfügen (z.B. als CKAN-Extension). 
 
**3.	**Leipzig App****  
Die Leipzig App bietet mehr als eine reine Linksammlung: Ab jetzt können bürgernahe Anwendungen bequem und intuitiv mit dem Smartphone bedient werden. Die App soll in den kommenden Jahren um weitere Funktionen ergänzt werden. 

**Die Challenges:** 
1.	Die Funktion Vereinsdatenbank bietet die Möglichkeit Vereine nach Stadtteil und Interessenlage individuell zu suchen und zu finden. Allerdings können Vereine zurzeit nur per E-Mail oder telefonisch hinzugefügt werden. Es wird nach einer technischen Möglichkeit gesucht, ein System zum automatisierten Eintragen von Vereinen in die App zu integrieren. 
2.	Die Leipzig App soll mit einem Wartezeitmanagement aufgewertet werden. Diese Funktion informiert die Bürger/-innen in Echtzeit über die aktuellen Wartezeiten in den Bürgerbüros. Aktuell gibt es eine programmiertechnische Herausforderung: Wie können wir sicherstellen, dass freie Warte-Slots nicht angezeigt werden, wenn die Bürgerbüros geschlossen sind?  
Ein Testsystem zum Gegenentwickeln wird im Rahmen des Hackathons zur Verfügung gestellt. 
 
**4.	Offenes Thema** 
Auf Wunsch können Beiträge rund um das Thema „Urbane Daten bspw. in Digitalen Zwillingen“ eingereicht werden. Unterschiedliche Ansätze und Themen sind willkommen. Im Fall der Wahl eines offenen Themas bitten wir um eine Kurzzusammenfassung des Vorhabens (ca. 150 Wörter) bei Anmeldung. 
 
Nähere Informationen erhalten Sie vom Referat Digitale Stadt der Stadt Leipzig. Anfragen können an digital[at]leipzig.de gerichtet werden. 
 
**### Wir freuen uns auf Ihre Teilnahme und sind gespannt auf die innovativen Ideen und Lösungsansätze – nicht nur in Form von Software, sondern wir begrüßen auch Einreichungen von Designs und Konzepten. Ergebnisse werden auf der Data Week am 15. April 2024 präsentiert und unter einer Open-Source-Lizenz auf [Open CoDE](https://opencode.de/de) veröffentlicht. Außerdem wird es pro Thema eine Prämie in Höhe von 1.000 € (1. Platz), 700 € (2. Platz) und 500 € (3. Platz) geben.**

**Comment by JuliaHolze** [comment]
You have not submitted an English text.

**Comment by splattater** [comment]
Current md version from staging
```
# 2. Leipziger Hackathon: Zugang zu Urbanen Datenplattformen für Bürger/-innen ermöglichen 

Unter dem Motto „Zugang zu Urbanen Datenplattformen für Bürger/-innen ermöglichen“ findet in diesem Jahr der 2. Leipzig Hackathon im Rahmen der Data Week statt. Ziel ist es, innovative Konzepte zu entwickeln, um städtische Daten effizienter und schneller zugänglich zu machen. 
Bürgerinnen und Bürger, Studierende, IT-Enthusiasten und Open-Data-Liebhaber sind herzlich eingeladen, die städtischen Anwendungen und Schnittstellen zu den Bürger/-innen mit eigenen Ideen und Vorschlägen zu bereichern. 

**Datum Hackathon:**  12. April - 13. April 2024, **Ort:** Smart City Lab (Magazingasse 3, 04109 Leipzig) 
**Präsentation und Preisverleihung** am 15. April (15:30 - 17:00 Uhr), **Ort:** Neues Rathaus Leipzig 
**Anmeldungen bis zum 01. April über [Digital@Leipzig.de](mailto:Digital@Leipzig.de) 
Bitte geben Sie bei der Anmeldung Name(n), E-Mail-Adresse(n) und das gewünschte Thema an.** 

Themen:  
**1. Digitale Karten spielend leicht verstehen lernen**
Kartenbasierte Beteiligungsplattformen werden zunehmend in städtischen Planungs- und Entwicklungsvorhaben eingesetzt, um mehr Einwohner/-innen aus unterschiedlichen Zielgruppen zu erreichen. Allerdings bringen diese Herausforderungen mit sich: Einerseits muss man die Anwendung selbst erlernen, was sich über Benutzerführung und Dokumentation erreichen lässt, andererseits müssen die Nutzer/-innen Karten und Geodaten selbstständig lesen, verstehen und verwenden können. Ziel ist es, Werkzeuge oder Ideen zu entwickeln, die diese Hürden überwinden. Wie finden wir eine „leichte Sprache” für Karten- und Geoinformationen? Wie lassen sich abstrakte Konzepte wie Kartenlayer und ihre Zusammenhänge für alle zugänglich machen?  
 
**2.	**Open Data Kataloge erschließen****  
Open Data Portale, wie das Leipziger, nutzen eine Vielzahl von verschiedenen Software-Lösungen, die unterschiedlichste Möglichkeiten anbieten, nach Datensätzen zu suchen und mit ihnen zu interagieren. Häufig sind diese Interfaces nicht barrierefrei oder nur für Expert/-innen zu bedienen, die schon wissen, wonach sie suchen. Für das in Leipzig eingesetzte CKAN wird derzeit auch erwogen, das Frontend grundsätzlich neu zu konzipieren.. 
Open Data konzentriert sich per Definition auf maschinenlesbare Daten, auch bei den veröffentlichten Metadaten-Katalogen. EU-weit veröffentlichen öffentliche Stellen diese nach dem Standard DCAT-AP. In der Regel lassen sie sich über eine einzige URL abrufen, wie auch [der Katalog des Open Data Portals Leipzig](https://opendata.leipzig.de/catalog.ttl). 
Wie kann man diese Kataloge besser zugänglich und durchsuchbar machen? Wie schlägt man eine Brücke von Amts- und Fachsprache zu den Fragen, die die Leipziger Bürger/-innen stellen? Können Assistenzsysteme wie Large Language Models dabei unterstützen? 
 
Wir freuen uns bei Software-Einreichungen besonders über solche, die auf accessible-by-design Frameworks (z.B. [KoliBri](https://public-ui.github.io/)) setzen, oder sich in die existierende Open-Source-Landschaft einfügen (z.B. als CKAN-Extension). 
 
**3. Leipzig App**
Die Leipzig App bietet mehr als eine reine Linksammlung: Ab jetzt können bürgernahe Anwendungen bequem und intuitiv mit dem Smartphone bedient werden. Die App soll in den kommenden Jahren um weitere Funktionen ergänzt werden. 

**Die Challenges:** 
1.	Die Funktion Vereinsdatenbank bietet die Möglichkeit Vereine nach Stadtteil und Interessenlage individuell zu suchen und zu finden. Allerdings können Vereine zurzeit nur per E-Mail oder telefonisch hinzugefügt werden. Es wird nach einer technischen Möglichkeit gesucht, ein System zum automatisierten Eintragen von Vereinen in die App zu integrieren. 
2.	Die Leipzig App soll mit einem Wartezeitmanagement aufgewertet werden. Diese Funktion informiert die Bürger/-innen in Echtzeit über die aktuellen Wartezeiten in den Bürgerbüros. Aktuell gibt es eine programmiertechnische Herausforderung: Wie können wir sicherstellen, dass freie Warte-Slots nicht angezeigt werden, wenn die Bürgerbüros geschlossen sind?  
Ein Testsystem zum Gegenentwickeln wird im Rahmen des Hackathons zur Verfügung gestellt. 
 
**4. Offenes Thema** 
Auf Wunsch können Beiträge rund um das Thema „Urbane Daten bspw. in Digitalen Zwillingen“ eingereicht werden. Unterschiedliche Ansätze und Themen sind willkommen. Im Fall der Wahl eines offenen Themas bitten wir um eine Kurzzusammenfassung des Vorhabens (ca. 150 Wörter) bei Anmeldung. 
 
Nähere Informationen erhalten Sie vom Referat Digitale Stadt der Stadt Leipzig. Anfragen können an digital[at]leipzig.de gerichtet werden. 
 
**Wir freuen uns auf Ihre Teilnahme und sind gespannt auf die innovativen Ideen und Lösungsansätze – nicht nur in Form von Software, sondern wir begrüßen auch Einreichungen von Designs und Konzepten. Ergebnisse werden auf der Data Week am 15. April 2024 präsentiert und unter einer Open-Source-Lizenz auf [Open CoDE](https://opencode.de/de) veröffentlicht. Außerdem wird es pro Thema eine Prämie in Höhe von 1.000 € (1. Platz), 700 € (2. Platz) und 500 € (3. Platz) geben.**
```
