### ISSUE TITLE
Add Event Description - KMi Konsortialtreffen

### ISSUE THREAD

**Issue by JuliaHolze** [AKSW/leipzig.dataweek.de#40]
Der Wandel von Unternehmen und Unternehmensprozessen, welcher angetrieben wird durch die breiten Möglichkeiten der Künstlichen Intelligenz und der damit einhergehenden Technologien, bietet Beschäftigten wie Organisationen zahlreiche Chancen, stellt diese aber gleichzeitig auch vor große Herausforderungen. Die Begleitung des Transformationsprozesses, welcher sich von der Erarbeitung konzeptioneller Ideen für den Einsatz KI-gestützter Methoden und Technologien über die Entwicklung prototypischer Lösungen bis hin zur Implementierung und Evaluation erstreckt, ist Inhalt des Projektes KMI (künstlich – menschlich – intelligent). Das gleichnamige Kompetenzzentrum verfolgt dabei stets einen menschzentrierten Ansatz, um die Nachhaltigkeit der entwickelten Lösungen sicherzustellen. Der Transformationsprozess orientiert sich demzufolge an den Bedarfen aller Beteiligten, insb. denen der Beschäftigten, und ist partizipativ zu verstehen. Dies umfasst die Konzeptionsphase und die initiale Anforderungserhebung, ebenso wie die Überführung der technologischen Lösung ins Operative. Im Rahmen der Data Week stellt sich das KMI Konsortium der interessierten Öffentlichkeit vor und gibt Einblicke in aktuelle Entwicklungen rund um KI in der Region des Mitteldeutschen Kohlereviers. 

The transformation of companies and business processes, driven by the broad possibilities of artificial intelligence and associated technologies, offers employees and organizations numerous opportunities but at the same time also confronts them with significant challenges. The KMI project (Artificial - Human - Intelligent) focuses on supporting this transformation process. Its scope ranges from the development of conceptual ideas for the use of AI-supported methods and technologies to the development of prototype solutions, their implementation and evaluation. The competence centre KMI pursues a human-centred approach to ensure the sustainability of the developed solutions. The transformation process is therefore geared to the needs of all those involved, especially the employees, and is to be understood as participatory. This includes the conception phase and initial requirements gathering, as well as the transfer of the technological solution into operations. During the Data Week, the KMI consortium will present itself to the interested public and provide insights into current developments around AI in the region of the Central German Coalfield.

**Comment by splattater** [comment]
done
