### ISSUE TITLE
Text on front page

### ISSUE THREAD

**Issue by JuliaHolze** [AKSW/leipzig.dataweek.de#402]
Please change text on the front page:

Ein Datenfestival für IT-Begeisterte! Die Data Week bietet ein einwöchiges Veranstaltungsprogramm rund um die Themenschwerpunkte Daten, Digitalisierung, künstliche Intelligenz und Herausforderungen der Stadtentwicklung.

**Comment by JuliaHolze** [comment]
AND
Die Organisatoren möchten auch Studierende, Auszubildende und interessierte Bürger:innen einladen, einen Blick hinter die Kulissen zu werfen oder an den verschiedenen Schulungen teilzunehmen, die während der Leipzig Data Week angeboten werden. Während der Data Week Leipzig finden mehrere Schulungen und Tutorien statt, die Einblicke in verschiedene Prinzipien, Techniken, Anwendungsfälle oder Datensätze geben.

The organisers would also like to invite students, trainees, and interested citizens to take a look behind the scenes or take part in the various training sessions offered during Data Week Leipzig. Several trainings and tutorials will take place during Data Week Leipzig and provide insight into different principles, techniques, use cases or data sets.

**Comment by splattater** [comment]
What should be changed for what? I'm a bit confused

**Comment by JuliaHolze** [comment]
Plese see here

![grafik](https://github.com/AKSW/leipzig.dataweek.de/assets/16899957/8b096c57-2da3-43ff-91a3-035c2a635d1c)

<img width="816" alt="Screenshot 2024-02-19 183717" src="https://github.com/AKSW/leipzig.dataweek.de/assets/16899957/c41cca86-2b57-4789-96ba-97d6e1d8c3ff">

**Comment by JuliaHolze** [comment]
This text was not changed:

Ein Datenfestival für IT-Begeisterte! Die Data Week bietet ein einwöchiges Veranstaltungsprogramm rund um die Themenschwerpunkte Daten, Digitalisierung, **_künstliche_** Intelligenz und Herausforderungen der Stadtentwicklung.

**Comment by JuliaHolze** [comment]
![grafik](https://github.com/AKSW/leipzig.dataweek.de/assets/16899957/9f8609de-26df-4ad0-a3a5-3d9a8eb81806)

**Comment by splattater** [comment]
part of pr #409
