### ISSUE TITLE
Add Event Description - European Innovation Day

### ISSUE THREAD

**Issue by JuliaHolze** [AKSW/leipzig.dataweek.de#41]
OGC is contributing to the Data Week Leipzig to reflect on current geospatial technologies and practices. With several topics, the main focus will be daily shifting from European data spaces and green deal (Monday), Urban planning (Tuesday) and semantic interoperability (Wednesday). Additionally, there are two days of the academic track with an emphasis on Artificial intelligence. 

It will particularly focus on the current capabilities and roles of local, regional, and national organizations and their evolving needs and challenges. The objective of the dataweek, with presentations, public discussions and workshops will be to identify requirements, priorities, and gaps for serving communities in the context of green deal sustainable development, including the challenges of disaster and climate circumstances.

There will be an opportunity to engage executive and director-level decision-makers and policymakers. It will go beyond green deal sustainable development to include innovations and strategies that produce actionable solutions and lead to improved interoperability across stakeholders, science domains, industry, and government.

OGC beteiligt sich an der Data Week Leipzig, um über aktuelle Geodaten-Technologien und -Praktiken zu reflektieren. Mit wechselnden Themen wird das Wochenprogramm der Data Week Leipzig ergänzt. So liegt am Montag der Schwerpunkt auf europäischen Datenräumen und dem Green Deal. Die Stadtplanung (Dienstag) und die semantische Interoperabilität (Mittwoch) folgen anschließend. Zusätzlich gibt es die angeschlossene AI Tomorrow Konferenz, die sich aus akademischer Sicht mit dem Thema künstliche Intelligenz beschäftigt.

Der Schwerpunkt des European Innovation Day (Dienstag) liegt auf den aktuellen Fähigkeiten und Rollen lokaler, regionaler und nationaler Organisationen und ihren sich entwickelnden Bedürfnissen und Herausforderungen. Ziel des OGC-Programms und der Data Week Leipzig ist es mit Präsentationen, öffentlichen Diskussionen und Workshops weitere Anforderungen, Prioritäten und Lücken für die Versorgung von Gemeinden im Rahmen einer nachhaltigen Entwicklung zu ermitteln, einschließlich der Herausforderungen von Katastrophen und Klimaverhältnissen.

Innerhalb des Tagungsprogramms werden u.a. politische Entscheidungsträger auf der Ebene von Führungskräften und Direktoren einbezogen. Die Themen werden über die nachhaltige Entwicklung im Rahmen des Green Deals hinausgehen und Innovationen sowie Strategien einbeziehen, die umsetzbare Lösungen hervorbringen und zu einer verbesserten Interoperabilität zwischen Interessengruppen, Wissenschaftsbereichen, Industrie und Regierungen führen.

**Comment by splattater** [comment]
Add event, team and abstract
