### ISSUE TITLE
UDS page - text changes

### ISSUE THREAD

**Issue by JuliaHolze** [AKSW/leipzig.dataweek.de#420]
Zur 3. Data Week Leipzig 2024 wird der neue Data Week-Partner, das Daten-Kompetenzzentrum für Städte und Regionen (DKSR) den Urban Data Summit (UDS) veranstalten. Offizieller Partner des UDS ist das Institut für ökologische Raumentwicklung (IÖR). Die Stadt Leipzig ist im Rahmen des UDS mit einzelnen Programmpunkten vertreten. 
Beim UDS steht die nachhaltige Kommunalgestaltung durch Daten und Digitalisierung im Vordergrund. Der Summit bietet ein interaktives Programm rund um digitale Anwendungen und Skalierbarkeit, das die Potenziale von Digitalisierung und Datennutzung in spezifischen städtischen Arbeitsbereichen aufzeigt. Dabei werden relevante kommunale Stakeholder:innen für flächendeckende datenbasierte Lösungen an einen Tisch gebracht und zum anwendungs- und maßnahmenorientierten Austausch sowie gemeinsamen Umsetzungen angeregt. Folgende Sessions sind im Rahmen des Urban Data Summits geplant:

### Vorträge:

**Kommunen für Kommunen – Wie gelingt die Replikation? (Stadt Leipzig & DKSR)**
Sitzungssaal, 11:00 - 12:30 

- Wissenstransfer und Replikation – viele Vorstellungen, wenig Klarheit (Elisabeth Breitenstein, Stadt Leipzig/Referat Digital Stadt)
- MPSC-Gelsenkirchen: Ein Anwendungszentrum für kommunale KI-Lösungen (Marlene Damerau, Gelsenkirchener Kommunale Datenzentrale Emscher-Lippe)
- TwinBy – Digitale Zwillinge für Bayern (Dr. Susanne Klöpping, Stefan Bobinger, Bayerisches Staatsministerium für Digitales)

**Kommunale Datenwerke: Datenteilen im rechtlich sicheren Rahmen (tbc)**

**Datenkompetenz in kommunalen Verwaltungen: Vorgehensmodell und Referenzrahmen für strategisches Handeln – Vorstellung eines Handlungsleitfadens für die kommunale Praxis (Johannes Sautter, Fraunhofer IAO)**

### Workshop
**Daten, Simulationen und Werkzeuge für nachhaltigen Wandel in Quartieren, Städten und Regionen (Input mit zwei anschließenden parallelen Tool-Vorstellungen/Workshops) (Leibniz-Institut für ökologische Raumentwicklung (IÖR)** 

- Kurze Vorstellung des Forschungsdatenzentrum des Leibniz-Instituts für ökologische Raumentwicklung (IÖR) IÖR-FDZ (Ramona Voshage)
- Toolvorstellung/Workshop A: 
GOAT-Workshop: Raum- und Mobilitätsdaten für eine integrierte und kollaborative Planung nutzbar machen (Eilias Parajes, Plan4Better GmbH, IÖR)

- Toolvorstellung/Workshop B: „Hochwasservorsorge im Blick: Das Informationstool FLOOD.Bi“ (Reinhard Schinke)

**Offene Daten in der Verwaltung: Chancen erkennen, Potentiale entfalten (Bianca Sammer, byte - Bayerische Agentur für Digitales & Tim Cleffmann, DKSR)**

**Vertrauenswürdige KI für Kommunen - wie geht das? (Anita Klingel, PD, Berater der öffentlichen Hand)**

**Die Reise von der gesamtheitlichen Smart City-Strategie zum digitalen Alltagsbegleiter für Bürger*innen: Das Beispiel Troisdorf (Max Schwerhoff, Stadt Troisdorf, Fabian Landua, DKSR)**

**Viele Wege führen zum Tool (Stadt Leipzig)**

- Chair: Dr. Christoph Schubert (Stadt Leipzig)
- Albert Steinbach (Stadt Halle (Saale)): Ausschreibung eines digitalen Zwillings in Halle (Saale) – Was es zu beachten gilt?
- Claudius Lieven (Stadt Hamburg): Die Dipas-Anwender-Community - Bericht vom Aufbau einer Open-Source Entwicklungsgemeinschaft
- Kim Strupp (Smarte KielRegion GmbH): Smart Beteiligt – die digitale Beteiligungs-Toolchain für Verwaltungen

**Smart City-Lösungen mit Daten aus dem Mobility Data Space (Dr. Tobias Miethaner, Mobility Data Space)**

**Learnings aus dem TwinBy-Projekt: Was macht einen guten Leitfaden zur Umsetzung Digitaler Zwillinge aus?**

**Datentreuhänder – Was sind geeignete Datenprodukte? (Marius Hupperz ISST, David Hick, DKSR, Marcel Altendeitering, Fraunhofer ISST)**

**Vom Sensor zur Analyse: Wie das "Internet of Things" die moderne Städteplanung revolutionieren kann (Fabian Landua, DKSR)**

**Die DKSR- Open Source-Datenplattform: Kommunale Mitbestimmung im Entwicklungsprozess (Magdalena Scharf & Tim Cleffmann, DKSR)**

**GeoGPT lokal: Interaktive Agenten in digitalen Landschaften (Holger Prang, Elie GmbH, Lukas Koch, DKSR)**

### Anmeldung zum Urban Data Summit und Ablauf
Bis auf wenige Vortragssessions, die für alle Data Week Teilnehmer*innen geöffnet sind, richtet sich der Urban Data Summit ausschließlich an Kommunale (Kommunen sowie kommunale Unternehmen). Diese haben die Möglichkeit, über DKSR einen Voucher zu erhalten, mit dem das Ticket für den 17. April bei der Data Week erworben werden kann (Anzahl begrenzt). Die Anmeldung verläuft daher zunächst über die [DKSR-Website](https://www.dksr.city/news-2/veranstaltungen/urban-data-summit-2024/). 

Kommunale, die sich für den Urban Data Summit anmelden, haben die Möglichkeit, über ihre Anmeldung für den 17. April auch an Veranstaltungen der Data Week/Der Stadt Leipzig am 16. April teilzunehmen (Kontingent begrenzt; Anmeldung ebenfalls über die [DKSR-Website](https://www.dksr.city/news-2/veranstaltungen/urban-data-summit-2024/).

**Comment by splattater** [comment]
@JuliaHolze einige Vorträge sind mit den "**" durcheinander gekommen. Sollen die mit in die Aufzählungen rein oder soll ich sie außerhalb der Aufzählung fett machen?

**Comment by splattater** [comment]
dank dir
