### ISSUE TITLE
Link Referat Digitale Stadt is broken

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#427]
The link for the Link Refereat Digitale Stadt is broken and returns 404:
https://chaos.social/@thomaskujawa@social.tchncs.de/112060376630880703

**Comment by white-gecko** [comment]
Neighter in the footer in the list of "Data Week In cooperation with" nor on the team page the link works.

**Comment by splattater** [comment]
Changed url to https://digitalcampus.leipzig.de/

**Comment by splattater** [comment]
@JuliaHolze please have a look if chosen url is ok and close issue or provide a new url.

**Comment by JuliaHolze** [comment]
https://digitalcampus.leipzig.de/ is correct.
