### ISSUE TITLE
Stream/Live page

### ISSUE THREAD

**Issue by JuliaHolze** [AKSW/leipzig.dataweek.de#435]
Please start preparing the live page with all youtube links, like in 2023 https://2023.dataweek.de/live.html.

**Comment by splattater** [comment]
Updated live.html. Organization of presenting the streams changed to a per-day-view (this year) from per-stream view (last year).
Chat/Discussion page must be updated to match the new view.

**Comment by white-gecko** [comment]
> Unter dem Stream wird "DataWeek2023 Stream A eccenca Corporate Memory DataWeek2023 Stream B" angezeigt. Das entspricht den Matrix Räumen, in denen der DataWeek bot ist. Die Stream URL nimmt sich das JavaScript immer aus dem Raum Topic, das heißt, als Administrator in dem Raum, kann man den Stream umstellen, den die Nutzer:innen zu sehen bekommen.
> Mit den Links hinter Montag, Dienstag, Mittwoch und Donnerstag also e.g. https://staging.dataweek.de/live/stream.html#!dFHhDmvNTjsDdFleJx:matrix.org kann man dem JavaScript jeweils mitteilen, welchen Matrix Raum es als erstes anzeigen soll.
- chat middleware is at https://github.com/AKSW/chat.dataweek.de
- and the chat interface at https://github.com/AKSW/lswt2021.stream (should only be needed for debugging purposes and to update the interface in the dataweek page, if required)

**Comment by white-gecko** [comment]
@seebi The middle-ware deployment should be updated with the latest container to work properly for this year.

**Comment by splattater** [comment]
chat rooms for 2024 are linked now. https://staging.dataweek.de/live/stream.html#
@seebi the bot needs to be restarted to forget the rooms of 2023.

**Comment by seebi** [comment]
I've just ask the @white-gecko public key so he can fix it.

**Comment by white-gecko** [comment]
The server part is restarted now and appears to work. Also the new chat rooms were created by @splattater .
Still the correct links need to be added to: https://2024.dataweek.de/live.html and a useful order of the channels needs to be implemented right below the video by @splattater .

**Comment by splattater** [comment]
As implement in https://github.com/AKSW/chat.dataweek.de matrix offers just room_id https://spec.matrix.org/legacy/client_server/r0.2.0.html to identify rooms and for a more friendly version the room name can be used.
We could implement it (a) in a way to use the room name to sort the rooms. Afterwards we could remove the string from the name that contains the information for the order. Or we use (b) another object in js which orders the rooms properly.

**Comment by white-gecko** [comment]
If you
a. write out the dict from https://github.com/AKSW/leipzig.dataweek.de/blob/6ddc7652a726593fda76f6589b713d35d42efba8/_config.yml#L13-L18 into a json object and then
b. sort the room list (i.e. `streamList`, it is the list of matrix rooms) according to the key in the dict from a in https://github.com/AKSW/leipzig.dataweek.de/blob/c592904e3e1b0a355c19a15c49c3b73fcee3c3cb/resources/js/chat.js#L65-L68
it should work

**Comment by splattater** [comment]
![image](https://github.com/AKSW/leipzig.dataweek.de/assets/1556061/15d7079f-de01-40e6-b7e1-cc93ffe6f9b2)
This works. Or I add prefixes and sort the stream_list for its values and delete the prefixes afterwards

**Comment by splattater** [comment]
stream_list contains this:
```{
  "!pEreTkmeqwWZPtAWpA:matrix.org": "LSWT2024",
  "!UPyDoiPIBTThTPDQXF:matrix.org": "Kommunen für Kommunen 1",
  "!wGwIOvxQCUcVwiKPQk:matrix.org": "Urban Data Summit",
  "!EgEHuNVtcBsfkKBzBJ:matrix.org": "Data Science Mania",
  "!LXXKyxfLmjTtRTzzAc:matrix.org": "Kommunen für Kommunen 2",
  "!irnMvwCKJtUyHjAAwI:matrix.org": "Menschen vernetzen - Daten nutzen"
}
```
and (b) would result in
```{
  "!pEreTkmeqwWZPtAWpA:matrix.org": "FLSWT2024",
  "!UPyDoiPIBTThTPDQXF:matrix.org": "CKommunen für Kommunen 1",
  "!wGwIOvxQCUcVwiKPQk:matrix.org": "EUrban Data Summit",
  "!EgEHuNVtcBsfkKBzBJ:matrix.org": "BData Science Mania",
  "!LXXKyxfLmjTtRTzzAc:matrix.org": "DKommunen für Kommunen 2",
  "!irnMvwCKJtUyHjAAwI:matrix.org": "AMenschen vernetzen - Daten nutzen"
}
```
if somebody uses matrix, room name would become ugly there

**Comment by white-gecko** [comment]
How about this: https://stackoverflow.com/questions/13304543/sort-a-javascript-array-based-on-another-array

**Comment by white-gecko** [comment]
I don't know if it works, but this would be a sketch:

```javascript
// flip streams so that we get
// "!irnMvwCKJtUyHjAAwI:matrix.org": stream_1_1
// instead of
// stream_1_1: "!irnMvwCKJtUyHjAAwI:matrix.org"
streams_flipped = Object.assign({}, ...Object.entries(streams).map(([a,b]) => ({ [b]: a })))

// sort streamList based on, the the keys of streams resp. the values of streams_flipped
streamList.sort(function(a, b){  
  return streams_flipped[a].localeCompare(streams_flipped[b]);
});
```

**Comment by splattater** [comment]
I just commited the code from the screenshot.
The main problem will be that we have further configuration from now on.
Maybe we can update the chat.js to a single room page (without buttons using the # value of the url) so the live.html is the page where users chose the room they want.

Or we use the menu features of the page to get static pages for each chat (needs further work on rdf model).
Let's discuss this next week at the dw.
