### ISSUE TITLE
Change Workshop Title and description ROOTS

### ISSUE THREAD

**Issue by varoe90** [AKSW/leipzig.dataweek.de#437]
please change the workshop title and description for the workshop on wednesday, 17.04. 
![grafik](https://github.com/AKSW/leipzig.dataweek.de/assets/92984623/06555afc-6f0b-4fb6-91fc-8da743fceb83)

to this text: 
Title:  "ROOTS: Non-Profits digital und partizipativ gestalten"

Text: "Angesichts digitaler und gesellschaftlicher Umbrüche, müssen sich auch Nonprofit-Organisationen (NPO) kontinuierlich weiterentwickeln. Anders jedoch als profitorientierte Unternehmen können sich NPO dabei nicht allein an effizienzsteigernden Maßnahmen orientieren. So müssen bspw. in einem Veränderungsprozess die Organisationswerte berücksichtigt werden. Im Workshop werden deshalb Wege aufgezeigt werden, wie sich NPO wertorientiert und partizipativ weiterentwickeln können. Dafür wird der Einsatz und Grenzen digitaler und KI-gestützter Werkzeuge i.S.d. Wertorientierung beleuchtet. Außerdem haben die Teilnehmende die Möglichkeit, Strategien zu entwickeln, wie sie digitale Mitwirkungsverfahren in der eigenen Organisation umsetzen können und es besteht die Möglichkeit sich mit anderen Organisationen auszutauschen und zu vernetzen. 

Der Workshop richtet sich an Vertreter:innen von NPO (Vereine, gGmbH, Genossenschaften u.a.)
Anmeldung erforderlich unter kmi-project@infai.org"

**Comment by splattater** [comment]
@varoe90 do you have an english version, too?

**Comment by varoe90** [comment]
ROOTS: Designing digital and participatory non-profit organisations"

Text: "In the face of digital and social upheaval, non-profit organisations (NPOs) undergo a continuous process of development. However, unlike profit-orientated companies, NPOs cannot focus solely on efficiency-enhancing measures. Therefore, organisational values must be taken into account in the design and implementation of change processes. This workshop will show ways in which NPOs can develop in a value-orientated and participatory manner. To this end, the use and limits of digital and AI-supported tools in terms of value orientation will be examined. Participants will also have the opportunity to develop strategies on how they can implement digital participation processes in their own organisation and will have the opportunity to exchange ideas and network with other organisations.

The workshop is aimed at representatives of NPOs (associations, gGmbHs, cooperatives, etc.)
Registration required at kmi-project@infai.org

Translated with DeepL.com (free version)
