### ISSUE TITLE
Add Event Description - Daten befreien

### ISSUE THREAD

**Issue by JuliaHolze** [AKSW/leipzig.dataweek.de#45]
Daten befreien! Kompetenzen und Tools für klimaangepasste Städte 

An Tag 2 der Data Week heißt es "Daten befreien! Kompetenzen und Tools für klimaangepasste Städte". Das Connected Urban Twins Projekt und weitere Vorhaben der Stadt zeigen hier ganz konkret wie Daten aus verschiedenen Datenquellen kombiniert und unter anderem durch den Einsatz von Digitalen Zwillingen wichtige Erkenntnisse für die Stadtentwicklung gewonnen werden. Darüber hinaus werden verschiedene Akteure aus Forschung, Verwaltung und Wirtschaft ihre Lösungen und Initiativen zur Gestaltung einer nachhaltigen und klimagerechten Stadtentwicklung präsentieren.

Free data! Competences and tools for climate-adapted cities 
On Day 2 of Data Week Leipzig, the theme is "Freeing Data! Skills and Tools for Climate-Adapted Cities". The Connected Urban Twins project and other city projects will show how data from different data sources can be combined and how important insights for urban development can be gained through the use of digital twins. In addition, various actors from research, administration and business will present their solutions and initiatives for sustainable and climate-friendly urban development.

**Comment by TBoonX** [comment]
Zu welchem Event gehört das? Oder ist das ne News?

**Comment by splattater** [comment]
Ist ein Event der Stadt. Hab es gerade hinzugefügt.
