### ISSUE TITLE
hackathon track - text change

### ISSUE THREAD

**Issue by JuliaHolze** [AKSW/leipzig.dataweek.de#450]
Please update this text
### 3. Leipzig App

Die Leipzig App bietet mehr als eine reine Linksammlung: Ab jetzt können bürgernahe Anwendungen bequem und intuitiv mit dem Smartphone bedient werden. Die App soll in den kommenden Jahren um weitere Funktionen ergänzt werden.

Die Challenges:

-     Die Funktion Vereinsdatenbank bietet die Möglichkeit Vereine nach Stadtteil und Interessenlage individuell zu suchen und zu finden. Allerdings können Vereine zurzeit nur per E-Mail oder telefonisch hinzugefügt werden. Es wird nach einer technischen Möglichkeit gesucht, ein System zum automatisierten Eintragen von Vereinen in die App zu integrieren.
-     Die Leipzig App soll mit einem Wartezeitmanagement aufgewertet werden. Diese Funktion informiert die Bürger/-innen in Echtzeit über die aktuellen Wartezeiten in den Bürgerbüros. Aktuell gibt es eine programmiertechnische Herausforderung: Wie können wir sicherstellen, dass freie Warte-Slots nicht angezeigt werden, wenn die Bürgerbüros geschlossen sind?
-     Ein Testsystem zum Gegenentwickeln wird im Rahmen des Hackathons zur Verfügung gestellt.

-> new text
### 3. Thema: News und Veranstaltungen in der Leipzig App  

Die Leipzig App informiert über Neuigkeiten und Veranstaltungen in Leipzig. In Zukunft wird sie erweitert, um ausführlicher über Veranstaltungshöhepunkte im Jahresverlauf zu berichten, darunter beispielsweise die UEFA 2024.  

**Die Challenge:** 

Die Screens für News und Veranstaltungen sollen konzeptionell in Richtung Usability, Ästhetik, Erinnerungswert und Zugänglichkeit angepasst werden. Dabei ist es wichtig, eine ansprechende Gestaltung zu entwickeln, die einen positiven Gesamteindruck hinterlässt. 

Zusätzlich soll ein Template für eine Themenseite entworfen werden, die nur bei besonderen Veranstaltungen aktiviert wird und leicht zugänglich ist. Die Struktur wird fest definiert sein, wobei sich lediglich die Informationen je nach Event ändern sollen. Die Seite ist darauf ausgerichtet, alle relevanten Informationen ansprechend und übersichtlich zu präsentieren. 

Eine kollaborative Webanwendung für die Zusammenarbeit, Ideenfindung und Gestaltung wird im Rahmen des Hackathons bereitgestellt.

**Comment by splattater** [comment]
Die Challenges:

- Die Funktion Vereinsdatenbank bietet die Möglichkeit Vereine nach Stadtteil und Interessenlage individuell zu suchen und zu finden. Allerdings können Vereine zurzeit nur per E-Mail oder telefonisch hinzugefügt werden. Es wird nach einer technischen Möglichkeit gesucht, ein System zum automatisierten Eintragen von Vereinen in die App zu integrieren.
- Die Leipzig App soll mit einem Wartezeitmanagement aufgewertet werden. Diese Funktion informiert die Bürger/-innen in Echtzeit über die aktuellen Wartezeiten in den Bürgerbüros. Aktuell gibt es eine programmiertechnische Herausforderung: Wie können wir sicherstellen, dass freie Warte-Slots nicht angezeigt werden, wenn die Bürgerbüros geschlossen sind?
- Ein Testsystem zum Gegenentwickeln wird im Rahmen des Hackathons zur Verfügung gestellt.

**Comment by JuliaHolze** [comment]
Please delete your text example.

**Comment by JuliaHolze** [comment]
we need to bring this online:
Die Challenge:

Die Screens für News und Veranstaltungen sollen konzeptionell in Richtung Usability, Ästhetik, Erinnerungswert und Zugänglichkeit angepasst werden. Dabei ist es wichtig, eine ansprechende Gestaltung zu entwickeln, die einen positiven Gesamteindruck hinterlässt.

Zusätzlich soll ein Template für eine Themenseite entworfen werden, die nur bei besonderen Veranstaltungen aktiviert wird und leicht zugänglich ist. Die Struktur wird fest definiert sein, wobei sich lediglich die Informationen je nach Event ändern sollen. Die Seite ist darauf ausgerichtet, alle relevanten Informationen ansprechend und übersichtlich zu präsentieren.

Eine kollaborative Webanwendung für die Zusammenarbeit, Ideenfindung und Gestaltung wird im Rahmen des Hackathons bereitgestellt.
