### ISSUE TITLE
Collect and provide slides

### ISSUE THREAD

**Issue by splattater** [AKSW/leipzig.dataweek.de#470]
We have collected the slides for the Data Week sessions (workshops, trainings) and the presentations in the GDrive. https://drive.google.com/drive/folders/153pPtWhSmB2e48iK1RkNo1nL9DyNJNw9?usp=sharing Could you please make them visible on the Data Week page? Either as a small clickable icon (as in 2022) or as a link behind the name of the presentation.

**Comment by white-gecko** [comment]
https://2024.dataweek.de/2024-04-19/Room260.html#09:00 -> https://zenodo.org/communities/saxfdm/

**Comment by JuliaHolze** [comment]
We have put all the slides that were made available to us online.
