### ISSUE TITLE
Please add news about the pre-event

### ISSUE THREAD

**Issue by JuliaHolze** [AKSW/leipzig.dataweek.de#499]
### Pre-Event zur Data Week Leipzig 2025

In diesem Jahr wird es als Warm-up zur Data Week 2025 erstmals ein Pre-Event geben. Freuen Sie sich auf einen inspirierenden Abend am 29. November 2024 ab 18.00 Uhr im Festsaal des Neuen Rathauses. Dort wird SPIEGEL-Bestsellerautor Dr. Peter Kreuz aus seinem neuen Werk lesen und mit dem Referat Digitale Stadt und dem Institut für Angewandte Informatik (InfAI) e.V. darüber diskutieren, wie Menschen ticken, die die Welt bewegen.
Weitere Informationen zur Veranstaltung und zur Anmeldung finden Sie hier: https://2025.dataweek.de/warm-up/ 

### Pre-event: Data Week Leipzig 2025

This year, there will be a pre-event as a warm-up to Data Week 2025 for the first time. Look forward to an inspiring evening on November 29, 2024 from 6 p.m. in the ballroom of the New Town Hall. There, SPIEGEL bestselling author Dr. Peter Kreuz will read from his new book and discuss with the Digital City Department and the Institute for Applied Computer Science (InfAI) e.V. what makes people who move the world tick.
Further information on the event and registration can be found here: https://2025.dataweek.de/en/warm-up/index.html

**Comment by splattater** [comment]
News added and it can be reviewed at https://staging.dataweek.de/news.html.
Please merge if everything is fine
