### ISSUE TITLE
add sponsoring news

### ISSUE THREAD

**Issue by JuliaHolze** [AKSW/leipzig.dataweek.de#501]
### Sponsoringpakete für die Data Week Leipzig 2025 online!
2024-09-10

Auch bei der nächsten Data Week besteht die Möglichkeit, als Sponsor:in teilzunehmen. Dafür können verschiedene Pakete - Gold, Silber und Bronze - gebucht werden, die sich dementsprechend unterscheiden. Bis zum 15. Februar 2025 können Sie noch von einem Frühbucherbonus profitieren.
Eine detaillierte Auflistung aller Pakete und Preise finden Sie auf [unserer Website](https://2025.dataweek.de/sponsoring.html).

### Sponsorship packages for Data Week Leipzig 2025 online!
2024-09-10

It will also be possible to become a sponsor of the next Data Week. There are various packages to choose from - Gold, Silver and Bronze. You can still benefit from an early bird bonus until 15 February 2025.
A full list of all packages and prices can be found on [our website](https://2025.dataweek.de/sponsoring.html).

@splattater Bei den anderen beiden Newsmeldungen steht eine falsche Jahreszahl, kannst du 2025 bitte in 2024 umschreiben? https://2025.dataweek.de/news.html

**Comment by splattater** [comment]
- News for sponsoring added
- dates fixed
These changes will be part of the pending pull request.
