### ISSUE TITLE
Please upload the Call for Participation for the LSWT 2025 to the Data Week website.

### ISSUE THREAD

**Issue by NievesECC** [AKSW/leipzig.dataweek.de#510]
Note: (same ticket as last time: https://github.com/AKSW/leipzig.dataweek.de/issues/330)
(There is no logo yet)

############################################
13. Leipziger Semantic Web Tag

Der Leipziger Semantic Web Tag (LSWT) ermöglicht seit 2009 WissenschaftlerInnen, Unternehmen und Organisationen, sich zu Themen im Bereich semantischer Technologien auszutauschen. Der **13. Leipziger Semantic Web Tag** (#LSWT2025) wird am **12. June 2025** im Rahmen der Data Week Leipzig stattfinden.
Wie auch schon in den Jahren davor werden die neuesten Entwicklungen und Trends in den Bereichen semantische Technologien und Daten präsentiert. **Schwerpunktthemen** in diesem Jahr sind: 

- Aktuelle Herausforderungen bei der Anwendung von Large Language Models
- Semantische Technologien und KI für Industrie und Wissenschaft
- Emerging Data Products
- Datenkompetenz und Sicherheit, einschließlich Cybersicherheit im Datenmanagement
- Wissensgraph-Anwendungsfälle und Nachhaltigkeit
- FAIR-Daten und Datenkataloge
- Vernetzte Gesellschaft

Falls Sie weitere Fragen haben, können Sie sich gern an das Organisationsteam wenden: lswt@eccenca.com.

**Aufruf zur Teilnahme** 
--> Download Link
[2024-12-02-LSWT2025-CFP-DE.pdf](https://github.com/user-attachments/files/17991560/2024-12-02-LSWT2025-CFP-DE.pdf)

Sind Sie bereit, einen Beitrag zu leisten? Wenn ja, laden wir Sie ein, Ihre aktuelle Arbeit in einem 15-minütigen Vortrag vorzustellen. Die Präsentationen werden in englischer Sprache gehalten. Über Beiträge von Frauen aus dem Bereich Data Science freuen wir uns besonders.

Wir freuen uns auf Ihre Beiträge, damit diese Veranstaltung ein Erfolg wird! **Bitte senden Sie Ihre Ideen für eine Präsentation bis zum 15.02.2025** an lswt@eccenca.com.

Wenn Sie weitere Fragen haben, zögern Sie nicht, uns zu kontaktieren. Wir freuen uns darauf, Sie in Leipzig zu treffen.

##############################################
13th Leipzig Semantic Web Day

Since 2009, the Leipzig Semantic Web Day (LSWT) is an opportunity for scientists, enterprises, and organisations to discuss topics in the field of Semantic Technology. The **13th Leipzig Semantic Web Day** (#LSWT2025) will once again be held in conjunction with the Data Week Leipzig on **June 12, 2025**, taking place in the heart of Leipzig.

During LSWT2024, we will highlight the latest developments and trends in semantic technologies and data. The focus topics for this year include: 

- Current Challenges in the Application of Large Language Models
- Semantic Technologies and AI for Industry and Science
- Emerging Data Products
- Data Competence and Security, including Cybersecurity in Data Management
- Knowledge Graph Use cases and Sustainability
- FAIR Data and Data Catalogs
- Networked Society

If you have any further questions don’t hesitate to contact the organisation team: lswt@eccenca.com.

**Call for Participation**
--> Download Link
[2024-12-02-LSWT2025-CFP-ENG.pdf](https://github.com/user-attachments/files/17991559/2024-12-02-LSWT2025-CFP-ENG.pdf)

If you are interested in participating, we invite you to present your current work in a 15-minute talk. Presentations will be held in English. We particularly welcome contributions from women in the field of Data Science. We look forward to your contributions to make this event a success! **Please send your ideas for a presentation until February 15, 2025** to lswt@eccenca.com.

If you have any further questions, don’t hesitate to contact us. We are looking forward to meeting you in Leipzig.

**Comment by splattater** [comment]
Can be reviewed on https://staging.dataweek.de/lswt2025. The download links for CfP pdf will work when merged to main.

**Comment by JuliaHolze** [comment]
@seebi Please review.

**Comment by NievesECC** [comment]
Hi @splattater please remove "Natanael" as part of Orgateam and then you can publish. Thank you very much
