### ISSUE TITLE
Bitte Track Seite für 2025 anlegen

### ISSUE THREAD

**Issue by JuliaHolze** [AKSW/leipzig.dataweek.de#511]
Bitte im Menü Tracks hinzufügen

https://2025.dataweek.de/tracks.html
https://2025.dataweek.de/en/tracks.html

Und die folgende Kachel:
LSWT
13. Leipziger Semantic Web Tag
Mi
2025-06-12
Der Leipziger Semantic Web Tag (LSWT) bietet seit 2009 WissenschaftlerInnen, Unternehmen und Organisationen die Möglichkeit, sich zu Themen im Bereich semantischer Technologien auszutauschen.

LSWT
13th Leipzig Semantic Web Day
Wed
2025-06-12
Since 2009, the Leipzig Semantic Web Day (LSWT) is an opportunity for scientists, enterprises, and organisations to discuss topics in the field of Semantic Technology.

**Comment by splattater** [comment]
fertig
