### ISSUE TITLE
Kurts resource has no rdfs:label

### ISSUE THREAD

**Issue by TBoonX** [AKSW/leipzig.dataweek.de#55]
The name is in the spreadsheet but still it does not get loaded into the final graph

**Comment by TBoonX** [comment]
Nate do you have a clue why my resource is handled differently.

**Comment by white-gecko** [comment]
I will take a look

**Comment by white-gecko** [comment]
Kurt is now on the page: https://next.dataweek.de/en/orgateam.html
There was a mismatch in the IRI, https vs. http
