### ISSUE TITLE
Add text - news section

### ISSUE THREAD

**Issue by JuliaHolze** [AKSW/leipzig.dataweek.de#56]
Please add the German Text on the website

Neue Website online!
Wir freuen uns sehr, pünktlich zur Data Week Leipzig 2023 unsere neue Website vorstellen zu können! Nach der ersten Data Week und einer erfolgreichen Konferenzwoche im Jahr 2022 sind wir als Organisationsteam in der Vorbereitungsphase für die kommende Data Week und haben in diesem Zuge die bisherige Netzwerkplattform ausgebaut und weiterentwickelt. Entdecken Sie unsere neue Webseite mit den neuesten Informationen zu Keynote-Speakern, Workshops und Networking-Events und beginnen Sie noch heute mit der Planung Ihrer Data Week Leipzig 2023.

**Comment by TBoonX** [comment]
Sorry, hatte beim programmieren was vergessen. ist jetzt drin
