### ISSUE TITLE
Extra Comma for Nils Hempelmann

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#58]
There is an extra comma.
![image](https://user-images.githubusercontent.com/1018168/215440282-6b9afe14-13db-40ce-b8dd-0598fd3667b5.png)

**Comment by white-gecko** [comment]
There is also an extra comma on the [Orgateam](https://next.dataweek.de/orgateam.html ) page.
![image](https://user-images.githubusercontent.com/1018168/215440819-5459e103-3798-4936-9d7a-acf2df5804c0.png)

**Comment by TBoonX** [comment]
I will fiy it now
