### ISSUE TITLE
Shift in the background for open tabs

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#60]
On my Firefox 108.0.1 there is a shift in the background image of active tabs.
![bitmap](https://user-images.githubusercontent.com/1018168/215442847-d1930369-71d7-4eb5-83ab-4dbeba36a0a1.png)

**Comment by TBoonX** [comment]
Depending on what we like more, there are two ways to use the background: (first is the current situation and the second is intended by Danny I assume)
![Screenshot from 2023-01-30 14-39-39](https://user-images.githubusercontent.com/3153545/215493802-493dcee3-5cd7-4b02-b529-104425cbe1ca.png)
![Screenshot from 2023-01-30 14-42-32](https://user-images.githubusercontent.com/3153545/215493817-f3f116ce-452c-41ad-88f9-f375cd0b38cc.png)
With the brighter background the tabs do look nicer I would say.

**Comment by dannyotto** [comment]
the shift is fixed

**Comment by white-gecko** [comment]
Where did you fix the shift? I can't find a commit on https://github.com/AKSW/leipzig.dataweek.de/commits/feature/newLayout

**Comment by dannyotto** [comment]
Because of my trouble yesterday with github, it's with some other fixes in one commit.

**Comment by dannyotto** [comment]
You only have to replace the css files.

**Comment by white-gecko** [comment]
To be solved with #88
