### ISSUE TITLE
Differences to the layout of the header bar

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#61]
There are some differences to the layout of the header bar:

- [x] The year is in a different blue
- [x] The language switch has complete language names
- [x] The date is shown in a different date format, no word, so no translation needed

Original Layout:
![image](https://user-images.githubusercontent.com/1018168/215443539-e61c0bbe-6caf-41aa-a0ce-827565b4f007.png)

Current "next" Layout
![image](https://user-images.githubusercontent.com/1018168/215443438-765213eb-79ce-4f14-bc04-5ee854907082.png)

**Comment by TBoonX** [comment]
Under which URL do you get the complete language names?
The different date values are `schema:date "26. bis 30.06.2023"@de, "June 26th to 30th, 2023"@en ;` which is fine from my point of view.

**Comment by splattater** [comment]
orange color got lost for language strings. issue still open

**Comment by TBoonX** [comment]
ALso the links are wrong. deutsch: /u and english: /g
But I do not see why

**Comment by TBoonX** [comment]
Fixed.
