### ISSUE TITLE
Background below tab bars

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#63]
The layout has a different background color for the content below tab bars

the layout:
![image](https://user-images.githubusercontent.com/1018168/215444813-5cf879e8-94d7-4ec7-bf57-ea20f025550f.png)

current implementation:

![image](https://user-images.githubusercontent.com/1018168/215445081-db90bf23-3241-4cab-a6b0-70a80470bf24.png)

**Comment by TBoonX** [comment]
Depending on what we like more, there are two ways to use the background: (first is the current situation and the second is intended by Danny I assume)
![Screenshot from 2023-01-30 14-39-39](https://user-images.githubusercontent.com/3153545/215493802-493dcee3-5cd7-4b02-b529-104425cbe1ca.png)
![Screenshot from 2023-01-30 14-45-43](https://user-images.githubusercontent.com/3153545/215494432-15d994fe-c3eb-4932-847d-8ee0b4277a75.png)

With the brighter background the tabs do look nicer I would say.
