### ISSUE TITLE
Starting page should include real text no dummy

### ISSUE THREAD

**Issue by TBoonX** [AKSW/leipzig.dataweek.de#68]

**Comment by JuliaHolze** [comment]
### Was ist die Data Week Leipzig?
Ein Datenfestival für IT-Begeisterte! Die Data Week bietet ein einwöchiges Veranstaltungsprogramm rund um die Themenschwerpunkte Daten, Digitalisierung, Künstliche Intelligenz und Herausforderungen der Stadtentwicklung. Anknüpfend an die erfolgreiche Konferenzwoche in 2022 wird die entstandene Netzwerkplattform nun erweitert und durch Kooperationen ausgebaut. Inhaltlich werden wissenschaftliche, wirtschaftliche und gesellschaftliche Perspektiven auf Daten und Künstliche Intelligenz aufgezeigt. 

Neue Partner in 2023 sind das Open Geospatial Consortium (OGC) und das Kompetenzzentrum Künstlich Menschlich Intelligent, welches die Working Conference on Artificial Intelligence Development for a Resilient and Sustainable Tomorrow organisiert. Mit den neuen Partnern soll die Bedeutung internationaler Datenräume für Strategien und Maßnahmen des Klimaschutzes hervorgehoben werden.  

- - -
A data festival for IT enthusiasts! Data Week offers a week-long programme of events focusing on data, digitalisation, artificial intelligence and urban development challenges. Following on from the successful conference week in 2022, the networking platform that has been created will now be expanded and developed through cooperation. The content will highlight scientific, economic and social perspectives on data and artificial intelligence. 

New partners in 2023 are the Open Geospatial Consortium (OGC) and the Competence Centre Artificial Human Intelligent, which is organising the Working Conference on Artificial Intelligence Development for a Resilient and Sustainable Tomorrow. The new partners aim to highlight the importance of international data spaces for climate change mitigation strategies and actions.  

### Zielgruppe
Industrie, Bürgerschaft, Wissenschaft und Behörden treten in einen Dialog – dies ist das Ziel der Data Week Leipzig 2023. Die bereits im letzten Jahr geschaffene Netzwerk- und Austauschplattform soll nun in Leipzig verstetigt werden. Besonderer Fokus liegt neben dem KI- und Datenschwerpunkt auch auf der Begegnung von Industrie- und Wissenschaftsvertreter:innen mit städtischen Behörden. 

Weiterhin werden in Workshops und Vorträgen internationale IT-Expert:innen neueste Anwendungsfälle, zum Beispiel von digitalen Stadt-Zwillingen, vorstellen. Auch möchten die Organisator:innen am Bildungsstandort Leipzig Studierende, Auszubildende und interessierte Bürger:innen zu einem Blick hinter die Kulissen einladen und so ein Forum für IT- und Datenbegeisterte schaffen. 

- - -
Industry, citizens, science and public authorities enter into dialogue - this is the goal of Data Week Leipzig 2023. The networking and exchange platform already created last year is now to be consolidated in Leipzig. In addition to the focus on AI and data, there will also be a special focus on bringing together representatives from industry and science with city authorities. 
Furthermore, international IT experts will present latest applications, for example digital city twins, in workshops and keynotes. The organisers would also like to invite students, trainees and interested citizens to take a look behind the scenes and thus create a forum for IT and data enthusiasts.
