### ISSUE TITLE
Media Queries for tabs need improvements

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#74]
Original issue forked to
- #87 -> media queries on front page.
- "to much text on front page" was solved by reducing the text.
- this issue -> media queries for tabs.

**Comment by white-gecko** [comment]
![image](https://user-images.githubusercontent.com/1018168/215737159-430991da-ee01-44be-9c04-f9049293d3ab.png)
![image](https://user-images.githubusercontent.com/1018168/215737286-6d8d154d-3396-476b-89c4-3b896e394f32.png)

**Comment by dannyotto** [comment]
In your screenshots there is too much text in the hero element and in the tabs as well.

<img width="831" alt="tabs" src="https://user-images.githubusercontent.com/869758/215858097-4d876e12-b2b3-42a8-a47a-1d42692bf5e0.png">

**Comment by white-gecko** [comment]
We have reduced the text in the Tabs already, but we will have probably 8 events in total, so we need the layout to work for 8 tabs.

**Comment by dannyotto** [comment]
Can I see the current implementation anywhere?

**Comment by white-gecko** [comment]
- The current code is here: https://github.com/AKSW/leipzig.dataweek.de/tree/next
- The built is on: https://github.com/AKSW/leipzig.dataweek.de/tree/page-next
- Served on: https://next.dataweek.de

**Comment by dannyotto** [comment]
<img width="1124" alt="Bildschirm­foto 2023-01-31 um 20 18 35" src="https://user-images.githubusercontent.com/869758/215860872-9141a719-2e24-400f-9c9b-e102f977bb9c.png">

**Comment by dannyotto** [comment]
There is a second navigation for more than one event on the same day.

**Comment by white-gecko** [comment]
So far we have decided to use one tab per sub event, we will revisit this and come back to you with a decision.

**Comment by dannyotto** [comment]
If you will use one tab per event instead of one tab per day, the layout needs to be adjusted, I think.

**Comment by dannyotto** [comment]
Maybe this problem will be fixed with a solution for #80 .

**Comment by white-gecko** [comment]
This is now part of #114.
