### ISSUE TITLE
The Pagetitle "Data Week Leipzig" is not dashy enough on mobile

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#75]
![image](https://user-images.githubusercontent.com/1018168/215509288-0850a984-e7e0-445c-ac52-1f9c5d93b96d.png)

**Comment by dannyotto** [comment]
I did it that way to save space. I just increased the title.

**Comment by white-gecko** [comment]
where did you increase it? here in the repo, in which branch?

**Comment by dannyotto** [comment]
I can't push. Is it possible that I don't have write permissions?

**Comment by white-gecko** [comment]
You are in the team and now also added with write permission, so you should be able to

**Comment by white-gecko** [comment]
Thank you, I like the solution.
![image](https://user-images.githubusercontent.com/1018168/216023397-d56d866e-ccaf-4796-99ec-6c7495441ec7.png)

It now needs to be taken over to the tempalte.

**Comment by dannyotto** [comment]
It's only CSS.

**Comment by white-gecko** [comment]
To be solved with #88
