### ISSUE TITLE
mobile: event selection does not work

### ISSUE THREAD

**Issue by TBoonX** [AKSW/leipzig.dataweek.de#80]
on my android phone with chrome browser if I select an event and click on show, the URL stays the same

**Comment by TBoonX** [comment]
I did add a tiny JS snippet to make it work

**Comment by white-gecko** [comment]
This snippet was added in https://github.com/AKSW/leipzig.dataweek.de/commit/56094f584dcdc1a1d1f1a58cfa5beeccd1cb985f

**Comment by white-gecko** [comment]
@dannyotto is this an acceptable solution or do you have the snippet in your code base?

**Comment by dannyotto** [comment]
I would use a server script for redirecting. Than it could work also without JavaScript. But your solution is fine too.

**Comment by white-gecko** [comment]
@TBoonX Do you have an idea how to solve this as a server script?

**Comment by TBoonX** [comment]
No, because the link has to be generated on the RDF iris.

**Comment by white-gecko** [comment]
Is replaced by #91
