### ISSUE TITLE
Impressions text is only displayed on the german version

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#84]
The text in the section "Impressions of the Data Week 2022" is only shown on the German page. An English translation is needed.

**Comment by JuliaHolze** [comment]
An exciting week of events for startups, students as well as representatives from science, administration and industry with more than 340 participants at the New City Hall Leipzig.
The week-long event at Leipzig's New Town Hall brought together stakeholders from business, science and administration over five days of events. What all participants from various disciplines had in common was an interest in topics of digitization, data and artificial intelligence. Commenting on this interdisciplinarity, Dr. Sebastian Tramp, CTO of eccenca GmbH, said, "With Data Week, we are broadening our scope from a purely academic event to one that can really interest everyone." The conference week was characterized by varied exchange and networking opportunities. Many presentations, workshops and discussion panels were organized. Furthermore, Data Week Leipzig opened on July 4, 2022 with the exciting keynote presentation "Of Errors in Data and Errors in Thinking" by Stefan Holtel (Curator for Digital Transformation at PricewaterhouseCoopers GmbH). All slides and presentations can be found on the Data Week 2022 website.
