### ISSUE TITLE
Highlight selection on mobile

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#85]
The mobile menu should also highlight the currently selected menu entry
Compare #62 .

**Comment by TBoonX** [comment]
the classes do not work - we need something from danny

**Comment by white-gecko** [comment]
This is in @dannyotto 's template:
https://github.com/AKSW/leipzig.dataweek.de/blob/b2a250ef0f58fcd677e5dcd93e176565e93560fd/organisationsteam_team-a.html#L120-L126

The menu entry has to be `<strong>` and not a link (no `<a>`-tag).

Maybe a class would be a better solution here or the same classes as for the desktop menu, but we should discuss this improvement with Danny later.

**Comment by splattater** [comment]
Do we discuss the highlighting behaviour of the default menu or of the mobile menu? https://github.com/AKSW/leipzig.dataweek.de/blob/b2a250ef0f58fcd677e5dcd93e176565e93560fd/organisationsteam_team-a.html#L253
Entries of the mobile menu use `<a>`

**Comment by white-gecko** [comment]
" Highlight selection on mobile #85 " of the mobile menu. Yes you are right, the snippet above was from the main menu, but the lines are the same, as far as I see, for the mobile menu:

https://github.com/AKSW/leipzig.dataweek.de/blob/b2a250ef0f58fcd677e5dcd93e176565e93560fd/organisationsteam_team-a.html#L303-L308

Playing around with the inspect tool, not being a link and adding strong tags did the difference.

**Comment by white-gecko** [comment]
This change introduced duplicate entry for organization team
![image](https://user-images.githubusercontent.com/1018168/216028912-cb09127e-25bc-43b8-b105-ee7665572e82.png)
