### ISSUE TITLE
Impressions picture show does not play automatically

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#86]
The impressions picture show does not play automatically through the pictures.

**Comment by dannyotto** [comment]
I have activated autoplay.

**Comment by white-gecko** [comment]
Where did you enable the autoplay? I can't find a commit on https://github.com/AKSW/leipzig.dataweek.de/commits/feature/newLayout

**Comment by dannyotto** [comment]
Like the other issues from yesterday, it's in one single commit. Sorry.

**Comment by white-gecko** [comment]
To be solved with #88

**Comment by white-gecko** [comment]
It still does not play: https://next.dataweek.de/

**Comment by dannyotto** [comment]
I had to generate the JS files again.
