### ISSUE TITLE
Media queries for front page need improvement.

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#87]
Forked from #74 .

**Screenshot 1**
![image](https://user-images.githubusercontent.com/1018168/215505920-bd64da44-4a76-4e46-8e71-532d9d83d10c.png)

**Screenshot 2**
![image](https://user-images.githubusercontent.com/1018168/215859576-1b7a7873-22b4-45dd-8422-ce54b00e523a.png)

**Screenshot 3**
![image](https://user-images.githubusercontent.com/1018168/215861577-e8fefccd-464a-475d-82c6-aef4bf62147e.png)

The issue of screenshot 1 was fixed already by reducing the text.

The issue of Screenshot 2 and 3 still exists.

**Comment by dannyotto** [comment]
This element was not layouted for more than a small amount of text. Now the image uses object-fit:cover also on small screens and the container has a min-height.

**Comment by white-gecko** [comment]
Thank you.
Unfortunately this still causes trouble for some mobile resolutions in the wide screen orientation.

![image](https://user-images.githubusercontent.com/1018168/216023113-56de9b1e-9d81-4d5b-87e9-e0279ebb8923.png)


![image](https://user-images.githubusercontent.com/1018168/216014139-c3d73ad9-a78e-4a81-95e1-8e4320d9519e.png)

**Comment by dannyotto** [comment]
I pushed a fix for this problem.

**Comment by white-gecko** [comment]
Thanks that works.

**Comment by white-gecko** [comment]
To be solved with #88
