### ISSUE TITLE
Mastodon Icon on Chrome/Chromium

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#89]
Maybe I did something wrong when I have added the mastodon icon in 38ee0c837e4036e68bab2ecd89ffdc8e4b13d163 .
It does not render properly on chromium (works on Firefox):
![image](https://user-images.githubusercontent.com/1018168/216037819-28ba500c-78bd-4ca0-b59c-1e91e52c75de.png)

@dannyotto are you able to fix this with your toolchain?

The icon is here: https://en.wikipedia.org/wiki/File:Mastodon_logotype_(simple)_new_hue.svg

**Comment by dannyotto** [comment]
I have added the icon. Maybe we now have to tweak the responsive views.

**Comment by white-gecko** [comment]
When I have tested it, it worked well. Thank you.
