### ISSUE TITLE
Tabs have an extra line on Chrome/Chromium

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#90]
Why I see the page on chromium, there is an extra line in the tabs. (Works on Firefox.)
![image](https://user-images.githubusercontent.com/1018168/216038302-1aee5bff-7f9b-48a1-adde-4ce5a4a1a2df.png)

**Comment by dannyotto** [comment]
I fixed this for chrome. Can you have a look in your browser please?
