### ISSUE TITLE
Change Mobile Event Selection

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#91]
Maybe we should just change the mobile event selection to something that works with one click, as it does in the desktop version.
This would mitigate #80 .
Also many of the visitors will use the page on their mobile devices throughout the week.

My suggestion would either
- be to have tiles in the set of the tabs in a flexible number of columns, or
- to show a list of the events that is clickable, just like in the mobile menu, but always visible.

cc: @JuliaHolze @seebi @TBoonX @splattater @MichaelMartin any ideas or comment?

**Comment by white-gecko** [comment]
Maybe something like
https://taskfile.dev/community/

![Screenshot_20230202-120843_Firefox](https://user-images.githubusercontent.com/1018168/216308906-70b12c5b-9225-4518-b2dd-4037649763a0.png)

**Comment by dannyotto** [comment]
Shall I add something like that?

**Comment by white-gecko** [comment]
yes. but in contrast to the taskfile page is should not be collapsed but just a list. if you have further questions just ask.

**Comment by dannyotto** [comment]
Not collapsed? Ok, than I will add just a list.

**Comment by dannyotto** [comment]
I'm not sure if everyone likes my solution, but you can have a look. You only have to replace the css files and remove the select form. There is no new html.

**Comment by white-gecko** [comment]
This is the solution in various widths:

![image](https://user-images.githubusercontent.com/1018168/217568390-5cc2807f-b83f-4516-8d94-308f3ae3a00c.png)
![image](https://user-images.githubusercontent.com/1018168/217568520-307444fb-e194-4721-a663-517bfe969a2e.png)
![image](https://user-images.githubusercontent.com/1018168/217568583-369acc3a-543e-4219-9cba-f3b3f578fba8.png)

I thought more about a menu that would highlight the selected item with the hatched background as we have it for the tabs. Alternatively we could use the same styling as for the Programmbereich A & B switch.

@TBoonX @splattater @JuliaHolze @MichaelMartin @seebi any comments from your site about the style for the tabs on mobile.

**Comment by dannyotto** [comment]
My first try was a dark blue box with highlighted items. But that was a complete new element and on a mobile devise in horizontal orientation it neads too much space. The current solution is a mix between mobil menue and the desktop version of this navigation.

There you can see it in the browser: https://prototype.pixelbrand.co/dataweek/programm_montag_bereich-a.html

**Comment by white-gecko** [comment]
This is now part of #114.
