### ISSUE TITLE
Further media selectors

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#93]
![image](https://user-images.githubusercontent.com/1018168/216060862-d244e0ff-45e7-4300-b44e-96fbf5ce7083.png)
![image](https://user-images.githubusercontent.com/1018168/216061223-a011e351-6973-48f1-a231-560298f3fce2.png)

734x606, 734x607, 734x608
![image](https://user-images.githubusercontent.com/1018168/216061473-10db1353-d98a-43f7-b46d-d0191b867030.png)
![image](https://user-images.githubusercontent.com/1018168/216061525-05020bca-772a-4479-916d-98caf3e442e1.png)
![image](https://user-images.githubusercontent.com/1018168/216061558-606c0bec-e197-4e6d-a4bb-8825bc326608.png)

**Comment by dannyotto** [comment]
Do you want to know, why there is no picture? Please check the path and the filename.
