### ISSUE TITLE
Serve media from https only

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#94]
There are some resources not yet served with relative paths.
![image](https://user-images.githubusercontent.com/1018168/216062853-077cf9b5-5e4d-42ce-8624-32e19009435c.png)

Actually I can't reproduce it with my network inspector. @splattater @TBoonX are you able to reproduce this?

**Comment by TBoonX** [comment]
I am not able to.

**Comment by white-gecko** [comment]
Fixed with #95 on staging, will be deployed with #106
