### ISSUE TITLE
Add contact information for individuals

### ISSUE THREAD

**Issue by white-gecko** [AKSW/leipzig.dataweek.de#98]
> ...dass weder beim Orgateam noch bei den verantwortlichen Personen für die Einzelveranstaltungen Kontaktdaten hinterlegt sind, das fände ich noch ganz gut umzusetzen

**Comment by white-gecko** [comment]
We need some way to add contact information, links, social links.
Our idea is to have icons in the person view.

Minimum 5 icons per person should fit in the layout

- phone
- homepage
- email
- linked in
- social stuff
- …

**Comment by dannyotto** [comment]
Ok. I can add the Icons. Would you prepare a list from this icons set please?

https://fontawesome.com/v5/cheatsheet
https://fontawesome.com/v5/cheatsheet/free/brands

**Comment by dannyotto** [comment]
I just added the icons. You can find the html code in organisationsteam_team-a.html.

**Comment by white-gecko** [comment]
![image](https://user-images.githubusercontent.com/1018168/217567714-372af987-b459-4d8d-8ba3-712d5a979e30.png)

**Comment by white-gecko** [comment]
@splattater or @TBoonX who can implement this in your templates? Many people should have a foaf:homepages already.
